var relatedPairs = {
   "White Center":[
      "Duwamish Boeing",
      "Southcenter",
      "Burien",
      "Capitol Hill",
      "Riverton Heights",
      "Sea-Tac",
      "Renton",
      "Seattle (Downtown)",
      "West Seattle Junction",
      "Bothell",
      "Renton Boeing",
      "Tukwila",
      "Beaux Arts",
      "Admiral District",
      "Beacon Hill",
      "Bellevue (Downtown)",
      "Delridge",
      "Newport Hills",
      "SODO",
      "First Hill",
      "Central District",
      "Sea-Tac Airport",
      "Georgetown",
      "Arbor Heights",
      "Fauntleroy",
      "Kennydale",
      "Gatewood"
   ],
   "Twin Lakes":[
      "Star Lake",
      "South Lake Union",
      "Kent",
      "Federal Way",
      "Seattle (Downtown)",
      "Midway",
      "Auburn",
      "Northeast Tacoma",
      "University District",
      "Ballard"
   ],
   "Bellevue (East)":[
      "Issaquah",
      "Redmond",
      "Overlake",
      "Eastgate",
      "University District",
      "Houghton",
      "Rose Hill",
      "Bellevue (Downtown)",
      "Education Hill",
      "Kirkland",
      "Montlake",
      "Medina",
      "Crossroads",
      "Clyde Hill",
      "Factoria"
   ],
   "Sammamish":[
      "Eastgate",
      "Overlake",
      "Redmond",
      "Issaquah",
      "Mercer Island",
      "Seattle (Downtown)",
      "Bellevue (Downtown)"
   ],
   "Covington":[
      "Kent",
      "Maple Valley",
      "Timberlane",
      "Kent East Hill",
      "Lake Meridian",
      "Seattle (Downtown)",
      "Midway"
   ],
   "Kent":[
      "Covington",
      "First Hill",
      "Georgetown",
      "Twin Lakes",
      "Sea-Tac",
      "Sea-Tac Airport",
      "Des Moines",
      "Kent East Hill",
      "Bellevue (Downtown)",
      "SODO",
      "Seattle (Downtown)",
      "Redmond",
      "Renton",
      "Burien",
      "Duwamish Boeing",
      "Kirkland",
      "Renton Boeing",
      "Lake Meridian",
      "Central District",
      "Kingsgate",
      "Totem Lake",
      "Newport Hills",
      "Maple Valley",
      "Tukwila",
      "University District",
      "Federal Way",
      "Midway",
      "Overlake",
      "Star Lake",
      "Southcenter",
      "Kennydale",
      "Timberlane",
      "Kent Boeing",
      "Auburn",
      "Houghton"
   ],
   "Eastlake":[
      "Capitol Hill",
      "Ravenna",
      "Seattle (Downtown)",
      "Wedgwood",
      "Montlake",
      "Lake City",
      "Maple Leaf",
      "University District",
      "Jackson Park",
      "South Lake Union",
      "Northgate"
   ],
   "Renton":[
      "Kennydale",
      "SODO",
      "Beaux Arts",
      "Houghton",
      "Maple Valley",
      "Bellevue (Downtown)",
      "Burien",
      "Sea-Tac Airport",
      "Eastgate",
      "Sea-Tac",
      "White Center",
      "Kent East Hill",
      "Medina",
      "Delridge",
      "Fairwood",
      "Bryn Mawr",
      "Kent",
      "Bothell",
      "Kingsgate",
      "Redmond",
      "Holly Park",
      "Shoreline",
      "Richmond Highlands",
      "Newport Hills",
      "Clyde Hill",
      "Kenmore",
      "Beacon Hill",
      "Montlake",
      "Factoria",
      "Totem Lake",
      "Overlake",
      "University District",
      "Rainier Beach",
      "Kirkland",
      "Seattle (Downtown)",
      "Tukwila",
      "Renton Boeing",
      "Skyway",
      "Auburn",
      "Southcenter",
      "Georgetown",
      "Riverton Heights",
      "Lake Forest Park",
      "Lake Meridian",
      "Renton Highlands",
      "Black Diamond",
      "Lake City"
   ],
   "Kirkland":[
      "Houghton",
      "Juanita",
      "Auburn",
      "Redmond",
      "Shoreline",
      "Factoria",
      "Woodinville",
      "Avondale",
      "Seattle (Downtown)",
      "South Kirkland",
      "University District",
      "Montlake",
      "Medina",
      "Bitter Lake",
      "Rose Hill",
      "Kent",
      "Newport Hills",
      "Lake Forest Park",
      "Totem Lake",
      "Bothell",
      "Bellevue (Downtown)",
      "Renton Boeing",
      "Richmond Highlands",
      "Overlake",
      "Eastgate",
      "Bellevue (East)",
      "Finn Hill",
      "Kennydale",
      "Wedgwood",
      "Renton",
      "Kenmore",
      "Crossroads",
      "Kingsgate",
      "Mercer Island"
   ],
   "Seattle (Downtown)":[
      "Beaux Arts",
      "Sand Point",
      "Wedgwood",
      "Central District",
      "Georgetown",
      "Innis Arden",
      "Rainier Valley",
      "North Bend",
      "Green Lake",
      "Northgate",
      "Kenmore",
      "Wallingford",
      "Kirkland",
      "Finn Hill",
      "SODO",
      "Ravenna",
      "South Kirkland",
      "Star Lake",
      "Ballard",
      "White Center",
      "Factoria",
      "Bitter Lake",
      "Medina",
      "Alki",
      "Kennydale",
      "Broadview",
      "Southcenter",
      "Kent",
      "Kent East Hill",
      "Eastlake",
      "Lake Meridian",
      "Montlake",
      "Richmond Beach",
      "Renton Highlands",
      "Shoreline",
      "Bothell",
      "Beacon Hill",
      "Vashon Island",
      "First Hill",
      "Woodinville",
      "Maple Valley",
      "Delridge",
      "West Seattle Junction",
      "Sammamish",
      "Black Diamond",
      "Issaquah",
      "Magnolia",
      "Madrona",
      "North City",
      "Crown Hill",
      "Mercer Island",
      "Fremont",
      "Maple Leaf",
      "Rose Hill",
      "Blue Ridge",
      "Totem Lake",
      "Twin Lakes",
      "South Lake Union",
      "Duwamish Boeing",
      "Queen Anne",
      "Fairwood",
      "Bellevue (Downtown)",
      "North Beach",
      "Timberlane",
      "Fauntleroy",
      "Clyde Hill",
      "Midway",
      "Rainier Beach",
      "Kingsgate",
      "Newport Hills",
      "Federal Way",
      "Jackson Park",
      "Gatewood",
      "Columbia City",
      "Phinney Ridge",
      "Eastgate",
      "Riverton Heights",
      "Covington",
      "Redmond",
      "Richmond Highlands",
      "Juanita",
      "Renton",
      "Lake City",
      "Tukwila",
      "Loyal Heights",
      "Overlake",
      "Auburn",
      "Burien",
      "Madison Park",
      "Des Moines",
      "University District",
      "Houghton",
      "Snoqualmie",
      "Skyway",
      "Kent Boeing",
      "Capitol Hill",
      "Lake Forest Park",
      "Arbor Heights",
      "Greenwood",
      "Admiral District",
      "Holly Park",
      "Normandy Park",
      "Mount Baker"
   ],
   "Totem Lake":[
      "Kenmore",
      "Lake Forest Park",
      "Kennydale",
      "Bellevue (Downtown)",
      "Kingsgate",
      "Richmond Highlands",
      "Bothell",
      "Renton Boeing",
      "Houghton",
      "Auburn",
      "University District",
      "Redmond",
      "Rose Hill",
      "Medina",
      "Juanita",
      "Kirkland",
      "Finn Hill",
      "Overlake",
      "Seattle (Downtown)",
      "Kent",
      "Renton",
      "Montlake",
      "South Kirkland",
      "Woodinville",
      "Newport Hills",
      "Shoreline"
   ],
   "Redmond":[
      "Houghton",
      "Finn Hill",
      "Kirkland",
      "Bothell",
      "Avondale",
      "Eastgate",
      "Cottage Lake",
      "Auburn",
      "South Kirkland",
      "Bellevue (Downtown)",
      "Bellevue (East)",
      "Duvall",
      "Montlake",
      "Overlake",
      "Crossroads",
      "Totem Lake",
      "Kent",
      "Sammamish",
      "Mercer Island",
      "Issaquah",
      "Medina",
      "Renton",
      "Green Lake",
      "Factoria",
      "Education Hill",
      "Seattle (Downtown)",
      "Renton Boeing",
      "Kingsgate",
      "Woodinville",
      "University District",
      "English Hill",
      "Kenmore",
      "Rose Hill"
   ],
   "Gatewood":[
      "SODO",
      "Tukwila",
      "Admiral District",
      "West Seattle Junction",
      "Fauntleroy",
      "Southcenter",
      "Riverton Heights",
      "Seattle (Downtown)",
      "Arbor Heights",
      "Delridge",
      "Vashon Island",
      "White Center"
   ],
   "Lake City":[
      "Sand Point",
      "Kenmore",
      "Northgate",
      "Southcenter",
      "Central District",
      "North Beach",
      "Clyde Hill",
      "First Hill",
      "Innis Arden",
      "University District",
      "Ravenna",
      "Wedgwood",
      "Loyal Heights",
      "Green Lake",
      "South Lake Union",
      "Eastlake",
      "Shoreline",
      "Medina",
      "Maple Leaf",
      "Bothell",
      "Seattle (Downtown)",
      "Jackson Park",
      "Bellevue (Downtown)",
      "Lake Forest Park",
      "Woodinville",
      "Montlake",
      "Renton"
   ],
   "Fremont":[
      "North Beach",
      "Greenwood",
      "Wallingford",
      "Phinney Ridge",
      "Crown Hill",
      "Northgate",
      "Ballard",
      "South Lake Union",
      "Broadview",
      "Innis Arden",
      "Magnolia",
      "Seattle (Downtown)",
      "Shoreline",
      "Queen Anne",
      "Blue Ridge",
      "Bitter Lake",
      "University District",
      "Green Lake"
   ],
   "Fairwood":[
      "SODO",
      "Renton",
      "Seattle (Downtown)",
      "Tukwila",
      "Southcenter"
   ],
   "Madison Park":[
      "Wedgwood",
      "Central District",
      "Bitter Lake",
      "Madrona",
      "Capitol Hill",
      "Seattle (Downtown)",
      "First Hill"
   ],
   "SODO":[
      "Columbia City",
      "Beacon Hill",
      "Renton",
      "Medina",
      "Alki",
      "Burien",
      "Admiral District",
      "Bothell",
      "West Seattle Junction",
      "Gatewood",
      "Seattle (Downtown)",
      "Kent",
      "Rainier Valley",
      "Southcenter",
      "Fairwood",
      "Shoreline",
      "Rainier Beach",
      "Delridge",
      "Riverton Heights",
      "Holly Park",
      "Federal Way",
      "Kennydale",
      "Montlake",
      "Bellevue (Downtown)",
      "Kent Boeing",
      "Skyway",
      "White Center",
      "Clyde Hill",
      "Newport Hills",
      "Tukwila",
      "Arbor Heights",
      "Georgetown",
      "Star Lake",
      "Auburn",
      "Richmond Highlands",
      "Vashon Island",
      "Fauntleroy",
      "Duwamish Boeing"
   ],
   "Kent Boeing":[
      "Kent East Hill",
      "Burien",
      "Southcenter",
      "SODO",
      "Sea-Tac",
      "Lake Meridian",
      "Auburn",
      "Tukwila",
      "Kent",
      "Seattle (Downtown)"
   ],
   "Kennydale":[
      "Renton",
      "Totem Lake",
      "Bellevue (Downtown)",
      "Kingsgate",
      "Tukwila",
      "Renton Boeing",
      "Clyde Hill",
      "Seattle (Downtown)",
      "Renton Highlands",
      "Sea-Tac",
      "Burien",
      "Bothell",
      "Newport Hills",
      "SODO",
      "Montlake",
      "Lake Forest Park",
      "Sea-Tac Airport",
      "Delridge",
      "Kirkland",
      "Richmond Highlands",
      "University District",
      "Medina",
      "Kenmore",
      "Shoreline",
      "Houghton",
      "Kent",
      "Auburn",
      "White Center",
      "Beaux Arts"
   ],
   "Riverton Heights":[
      "Duwamish Boeing",
      "Southcenter",
      "Fauntleroy",
      "White Center",
      "Burien",
      "Admiral District",
      "West Seattle Junction",
      "SODO",
      "Gatewood",
      "Renton Boeing",
      "Seattle (Downtown)",
      "Georgetown",
      "Delridge",
      "Renton",
      "Tukwila"
   ],
   "Rainier Beach":[
      "Rainier Valley",
      "Skyway",
      "Holly Park",
      "SODO",
      "South Lake Union",
      "Columbia City",
      "Georgetown",
      "Mount Baker",
      "Bothell",
      "Capitol Hill",
      "Bryn Mawr",
      "Seattle (Downtown)",
      "Queen Anne",
      "Renton",
      "Wedgwood",
      "First Hill",
      "Central District",
      "Bitter Lake",
      "Beacon Hill"
   ],
   "Greenwood":[
      "Fremont",
      "Richmond Highlands",
      "South Lake Union",
      "Green Lake",
      "Montlake",
      "Rainier Valley",
      "Broadview",
      "Loyal Heights",
      "Wallingford",
      "Crown Hill",
      "University District",
      "Blue Ridge",
      "Ballard",
      "Central District",
      "Innis Arden",
      "North Beach",
      "Bitter Lake",
      "Queen Anne",
      "Shoreline",
      "Mount Baker",
      "Phinney Ridge",
      "Seattle (Downtown)"
   ],
   "Harbor Island":[
      "Carnation"
   ],
   "Enumclaw":[
      "Auburn",
      "Muckleshoot Reservation"
   ],
   "North Bend":[
      "Seattle (Downtown)",
      "Bellevue (Downtown)",
      "Snoqualmie",
      "Fall City",
      "Eastgate",
      "Issaquah",
      "Preston"
   ],
   "Bryn Mawr":[
      "Skyway",
      "Renton",
      "Rainier Beach"
   ],
   "Tukwila":[
      "Star Lake",
      "Montlake",
      "Central District",
      "Federal Way",
      "Kennydale",
      "Newport Hills",
      "Admiral District",
      "Gatewood",
      "White Center",
      "Renton Boeing",
      "Southcenter",
      "Duwamish Boeing",
      "Delridge",
      "McMicken Heights",
      "Clyde Hill",
      "Kent",
      "Fairwood",
      "Lake Meridian",
      "Georgetown",
      "Kent East Hill",
      "Sea-Tac",
      "First Hill",
      "SODO",
      "Seattle (Downtown)",
      "Renton",
      "Fauntleroy",
      "Kent Boeing",
      "Burien",
      "Medina",
      "Midway",
      "Des Moines",
      "Bellevue (Downtown)",
      "West Seattle Junction",
      "Riverton Heights"
   ],
   "Muckleshoot Reservation":[
      "Auburn",
      "Enumclaw"
   ],
   "Innis Arden":[
      "Seattle (Downtown)",
      "Fremont",
      "Lake City",
      "Bitter Lake",
      "Richmond Highlands",
      "Phinney Ridge",
      "South Lake Union",
      "Shoreline",
      "Kenmore",
      "Greenwood",
      "Jackson Park",
      "Lake Forest Park",
      "Northgate",
      "Broadview",
      "University District",
      "Richmond Beach"
   ],
   "Delridge":[
      "Renton Boeing",
      "Capitol Hill",
      "Arbor Heights",
      "West Seattle Junction",
      "Beacon Hill",
      "Admiral District",
      "Renton",
      "SODO",
      "Bothell",
      "Southcenter",
      "Beaux Arts",
      "Seattle (Downtown)",
      "Tukwila",
      "White Center",
      "Central District",
      "First Hill",
      "Burien",
      "Georgetown",
      "Sea-Tac Airport",
      "Sea-Tac",
      "Kennydale",
      "Riverton Heights",
      "Fauntleroy",
      "Newport Hills",
      "Alki",
      "Bellevue (Downtown)",
      "Gatewood",
      "Duwamish Boeing"
   ],
   "Phinney Ridge":[
      "Montlake",
      "Fremont",
      "South Lake Union",
      "Crown Hill",
      "Shoreline",
      "Innis Arden",
      "Green Lake",
      "Richmond Highlands",
      "Ballard",
      "University District",
      "Seattle (Downtown)",
      "Blue Ridge",
      "Greenwood",
      "Broadview",
      "Bitter Lake",
      "Wallingford",
      "Queen Anne"
   ],
   "West Seattle Junction":[
      "Delridge",
      "SODO",
      "White Center",
      "Gatewood",
      "Riverton Heights",
      "Seattle (Downtown)",
      "Admiral District",
      "Beacon Hill",
      "Arbor Heights",
      "Columbia City",
      "Fauntleroy",
      "Alki",
      "Rainier Valley",
      "Southcenter",
      "Tukwila"
   ],
   "Rainier Valley":[
      "Columbia City",
      "Rainier Beach",
      "Queen Anne",
      "Seattle (Downtown)",
      "Green Lake",
      "Alki",
      "Greenwood",
      "SODO",
      "Capitol Hill",
      "First Hill",
      "North Beach",
      "Bitter Lake",
      "Montlake",
      "Wedgwood",
      "University District",
      "Holly Park",
      "South Lake Union",
      "Mount Baker",
      "Loyal Heights",
      "West Seattle Junction",
      "Admiral District",
      "Crown Hill",
      "Beacon Hill",
      "Central District"
   ],
   "Newport Hills":[
      "Bellevue (Downtown)",
      "Sea-Tac",
      "Lake Forest Park",
      "Tukwila",
      "Sea-Tac Airport",
      "Montlake",
      "Richmond Highlands",
      "Shoreline",
      "Beaux Arts",
      "Kirkland",
      "Burien",
      "Kenmore",
      "Auburn",
      "Renton",
      "Kennydale",
      "White Center",
      "Renton Boeing",
      "Renton Highlands",
      "Kent",
      "Seattle (Downtown)",
      "Eastgate",
      "Bothell",
      "SODO",
      "Kingsgate",
      "Factoria",
      "University District",
      "Houghton",
      "Delridge",
      "Medina",
      "Totem Lake",
      "Clyde Hill"
   ],
   "Jackson Park":[
      "South Lake Union",
      "Lake Forest Park",
      "Montlake",
      "Wedgwood",
      "Clyde Hill",
      "University District",
      "Bitter Lake",
      "Green Lake",
      "Medina",
      "Shoreline",
      "Maple Leaf",
      "First Hill",
      "Seattle (Downtown)",
      "Overlake",
      "Central District",
      "Richmond Highlands",
      "Innis Arden",
      "Bellevue (Downtown)",
      "Eastlake",
      "Lake City",
      "North City",
      "Broadview",
      "Northgate",
      "Richmond Beach",
      "Ravenna"
   ],
   "Capitol Hill":[
      "Bitter Lake",
      "Delridge",
      "Eastlake",
      "White Center",
      "Georgetown",
      "Rainier Valley",
      "Queen Anne",
      "Central District",
      "Montlake",
      "Holly Park",
      "Rainier Beach",
      "Columbia City",
      "First Hill",
      "Madrona",
      "Madison Park",
      "Duwamish Boeing",
      "University District",
      "South Lake Union",
      "Beacon Hill",
      "Seattle (Downtown)"
   ],
   "English Hill":[
      "Avondale",
      "Bothell",
      "Woodinville",
      "Redmond",
      "Cottage Lake"
   ],
   "Blue Ridge":[
      "Queen Anne",
      "Bitter Lake",
      "Ballard",
      "South Lake Union",
      "Seattle (Downtown)",
      "Greenwood",
      "Fremont",
      "Broadview",
      "Phinney Ridge",
      "Crown Hill"
   ],
   "Timberlane":[
      "Kent East Hill",
      "Covington",
      "Maple Valley",
      "Midway",
      "Seattle (Downtown)",
      "Lake Meridian",
      "Kent"
   ],
   "Kenmore":[
      "Totem Lake",
      "Shoreline",
      "Seattle (Downtown)",
      "Lake City",
      "Southcenter",
      "First Hill",
      "Bothell",
      "Woodinville",
      "Wedgwood",
      "Renton Boeing",
      "South Lake Union",
      "Newport Hills",
      "Lake Forest Park",
      "Richmond Highlands",
      "Houghton",
      "Renton",
      "Ravenna",
      "Innis Arden",
      "Bellevue (Downtown)",
      "Finn Hill",
      "Juanita",
      "Kirkland",
      "Maple Leaf",
      "Kennydale",
      "Overlake",
      "Kingsgate",
      "South Kirkland",
      "University District",
      "Redmond"
   ],
   "Madrona":[
      "South Lake Union",
      "Seattle (Downtown)",
      "Central District",
      "Madison Park",
      "Queen Anne",
      "Wedgwood",
      "Capitol Hill",
      "Bitter Lake",
      "Mount Baker",
      "First Hill"
   ],
   "Duvall":[
      "Bellevue (Downtown)",
      "Cottage Lake",
      "Redmond",
      "Avondale",
      "Overlake"
   ],
   "Richmond Beach":[
      "Seattle (Downtown)",
      "Richmond Highlands",
      "North City",
      "Shoreline",
      "Northgate",
      "Bitter Lake",
      "Jackson Park",
      "Broadview",
      "Innis Arden"
   ],
   "Carnation":[
      "Harbor Island"
   ],
   "Education Hill":[
      "Bellevue (Downtown)",
      "Eastgate",
      "Bellevue (East)",
      "Redmond",
      "Crossroads"
   ],
   "Queen Anne":[
      "Rainier Valley",
      "Broadview",
      "Magnolia",
      "Blue Ridge",
      "Wallingford",
      "South Lake Union",
      "Crown Hill",
      "First Hill",
      "Central District",
      "Capitol Hill",
      "Green Lake",
      "Seattle (Downtown)",
      "Madrona",
      "Fremont",
      "Northgate",
      "Wedgwood",
      "North Beach",
      "Rainier Beach",
      "Bitter Lake",
      "Ballard",
      "Greenwood",
      "Holly Park",
      "University District",
      "Loyal Heights",
      "Phinney Ridge"
   ],
   "Loyal Heights":[
      "Central District",
      "Green Lake",
      "University District",
      "Greenwood",
      "Lake City",
      "North Beach",
      "Mount Baker",
      "South Lake Union",
      "Sand Point",
      "Seattle (Downtown)",
      "Rainier Valley",
      "Ballard",
      "Queen Anne",
      "Montlake",
      "Northgate",
      "Crown Hill"
   ],
   "South Kirkland":[
      "Kingsgate",
      "Redmond",
      "Kirkland",
      "Finn Hill",
      "Seattle (Downtown)",
      "Bitter Lake",
      "Eastgate",
      "University District",
      "Totem Lake",
      "Overlake",
      "Houghton",
      "Juanita",
      "Montlake",
      "Kenmore",
      "Mercer Island",
      "Medina",
      "Bellevue (Downtown)",
      "Wedgwood"
   ],
   "Crown Hill":[
      "Ballard",
      "Fremont",
      "Phinney Ridge",
      "Magnolia",
      "University District",
      "Queen Anne",
      "Greenwood",
      "Seattle (Downtown)",
      "Central District",
      "South Lake Union",
      "Green Lake",
      "Bitter Lake",
      "Broadview",
      "Blue Ridge",
      "North Beach",
      "Mount Baker",
      "Rainier Valley",
      "Montlake",
      "Northgate",
      "Loyal Heights"
   ],
   "Fauntleroy":[
      "Southcenter",
      "Riverton Heights",
      "Arbor Heights",
      "Gatewood",
      "Seattle (Downtown)",
      "Vashon Island",
      "West Seattle Junction",
      "Delridge",
      "White Center",
      "Tukwila",
      "Admiral District",
      "SODO"
   ],
   "Avondale":[
      "Redmond",
      "Rose Hill",
      "Kirkland",
      "Bothell",
      "Bellevue (Downtown)",
      "English Hill",
      "Duvall",
      "Cottage Lake",
      "Woodinville",
      "Overlake"
   ],
   "Lake Meridian":[
      "Kent East Hill",
      "Seattle (Downtown)",
      "Auburn",
      "Covington",
      "Kent",
      "Maple Valley",
      "Tukwila",
      "Midway",
      "Kent Boeing",
      "Timberlane",
      "Renton"
   ],
   "Renton Boeing":[
      "Bellevue (Downtown)",
      "Overlake",
      "Delridge",
      "Auburn",
      "Kennydale",
      "Eastgate",
      "Totem Lake",
      "Richmond Highlands",
      "Beaux Arts",
      "White Center",
      "Tukwila",
      "Kenmore",
      "Kent",
      "Kirkland",
      "Factoria",
      "Riverton Heights",
      "Newport Hills",
      "Sea-Tac",
      "Shoreline",
      "Lake Forest Park",
      "Southcenter",
      "Kingsgate",
      "Houghton",
      "Burien",
      "Redmond",
      "Renton",
      "Renton Highlands",
      "Bothell",
      "Sea-Tac Airport"
   ],
   "Houghton":[
      "Kirkland",
      "Medina",
      "Redmond",
      "Renton",
      "Bothell",
      "Richmond Highlands",
      "Factoria",
      "Rose Hill",
      "Totem Lake",
      "Overlake",
      "Crossroads",
      "Auburn",
      "Lake Forest Park",
      "Bellevue (East)",
      "Bitter Lake",
      "Shoreline",
      "Bellevue (Downtown)",
      "University District",
      "Kenmore",
      "Kingsgate",
      "Eastgate",
      "Wedgwood",
      "Montlake",
      "South Kirkland",
      "Renton Boeing",
      "Newport Hills",
      "Kennydale",
      "Seattle (Downtown)",
      "Juanita",
      "Kent",
      "Finn Hill"
   ],
   "First Hill":[
      "Shoreline",
      "Northgate",
      "Kent",
      "Star Lake",
      "Kenmore",
      "Columbia City",
      "Lake City",
      "Beacon Hill",
      "Rainier Valley",
      "Queen Anne",
      "Seattle (Downtown)",
      "Lake Forest Park",
      "Green Lake",
      "Bitter Lake",
      "Central District",
      "Duwamish Boeing",
      "South Lake Union",
      "Eastgate",
      "Jackson Park",
      "White Center",
      "Federal Way",
      "Delridge",
      "Tukwila",
      "Capitol Hill",
      "Georgetown",
      "Mercer Island",
      "Richmond Highlands",
      "Ravenna",
      "Madrona",
      "University District",
      "Issaquah",
      "Madison Park",
      "Rainier Beach",
      "Wedgwood",
      "Mount Baker",
      "Midway"
   ],
   "Sea-Tac":[
      "Sea-Tac Airport",
      "Newport Hills",
      "White Center",
      "Renton",
      "Kent",
      "Des Moines",
      "Federal Way",
      "Kennydale",
      "McMicken Heights",
      "Bellevue (Downtown)",
      "Southcenter",
      "Beaux Arts",
      "Renton Boeing",
      "Tukwila",
      "Kent Boeing",
      "Auburn",
      "Delridge",
      "Burien"
   ],
   "Northeast Tacoma":[
      "Twin Lakes",
      "Federal Way"
   ],
   "Beacon Hill":[
      "SODO",
      "Delridge",
      "Skyway",
      "First Hill",
      "Duwamish Boeing",
      "Bothell",
      "Seattle (Downtown)",
      "White Center",
      "Admiral District",
      "Renton",
      "West Seattle Junction",
      "Columbia City",
      "Central District",
      "Alki",
      "Capitol Hill",
      "Holly Park",
      "Rainier Valley",
      "Georgetown",
      "Rainier Beach"
   ],
   "Renton Highlands":[
      "Factoria",
      "Kennydale",
      "Seattle (Downtown)",
      "Eastgate",
      "Beaux Arts",
      "Bellevue (Downtown)",
      "Newport Hills",
      "Bothell",
      "Renton",
      "Renton Boeing"
   ],
   "Green Lake":[
      "Loyal Heights",
      "North City",
      "Rainier Valley",
      "Seattle (Downtown)",
      "Mount Baker",
      "North Beach",
      "Greenwood",
      "Wallingford",
      "Jackson Park",
      "Queen Anne",
      "First Hill",
      "Bitter Lake",
      "Phinney Ridge",
      "Lake City",
      "Redmond",
      "Wedgwood",
      "Ravenna",
      "Crown Hill",
      "Northgate",
      "Maple Leaf",
      "Medina",
      "Montlake",
      "Central District",
      "University District",
      "Richmond Highlands",
      "Overlake",
      "Fremont",
      "South Lake Union",
      "Shoreline"
   ],
   "Woodinville":[
      "Kingsgate",
      "Cottage Lake",
      "Kirkland",
      "Kenmore",
      "Ravenna",
      "Seattle (Downtown)",
      "Maple Leaf",
      "Wedgwood",
      "Medina",
      "Totem Lake",
      "Montlake",
      "Juanita",
      "English Hill",
      "Avondale",
      "Bellevue (Downtown)",
      "Redmond",
      "Lake Forest Park",
      "Bothell",
      "Lake City",
      "University District"
   ],
   "North City":[
      "Green Lake",
      "Northgate",
      "Shoreline",
      "Montlake",
      "Overlake",
      "Richmond Beach",
      "Seattle (Downtown)",
      "Medina",
      "Maple Leaf",
      "Jackson Park",
      "Richmond Highlands"
   ],
   "Fall City":[
      "North Bend",
      "Snoqualmie",
      "Issaquah",
      "Preston"
   ],
   "Rose Hill":[
      "Avondale",
      "Crossroads",
      "Houghton",
      "Bellevue (Downtown)",
      "Juanita",
      "Factoria",
      "Medina",
      "University District",
      "Finn Hill",
      "Kirkland",
      "Montlake",
      "Totem Lake",
      "Kingsgate",
      "Bellevue (East)",
      "Seattle (Downtown)",
      "Bothell",
      "Eastgate",
      "Overlake",
      "Redmond"
   ],
   "Wedgwood":[
      "Madison Park",
      "Jackson Park",
      "Seattle (Downtown)",
      "Mount Baker",
      "Northgate",
      "South Lake Union",
      "Lake Forest Park",
      "Ravenna",
      "Kenmore",
      "Eastgate",
      "Eastlake",
      "Lake City",
      "University District",
      "Overlake",
      "Mercer Island",
      "Rainier Valley",
      "Woodinville",
      "Green Lake",
      "Clyde Hill",
      "Houghton",
      "Central District",
      "Queen Anne",
      "Bothell",
      "Madrona",
      "Maple Leaf",
      "Montlake",
      "Medina",
      "Kirkland",
      "Ballard",
      "Sand Point",
      "Bitter Lake",
      "Rainier Beach",
      "Magnolia",
      "Bellevue (Downtown)",
      "First Hill",
      "South Kirkland"
   ],
   "Admiral District":[
      "SODO",
      "Tukwila",
      "Delridge",
      "Gatewood",
      "Riverton Heights",
      "White Center",
      "Columbia City",
      "Beacon Hill",
      "West Seattle Junction",
      "Southcenter",
      "Alki",
      "Rainier Valley",
      "Seattle (Downtown)",
      "Fauntleroy"
   ],
   "Magnolia":[
      "Wallingford",
      "Queen Anne",
      "Crown Hill",
      "Ballard",
      "Fremont",
      "Seattle (Downtown)",
      "Bitter Lake",
      "Wedgwood",
      "University District"
   ],
   "Duwamish Boeing":[
      "White Center",
      "Riverton Heights",
      "Star Lake",
      "Beacon Hill",
      "Tukwila",
      "Kent",
      "Federal Way",
      "First Hill",
      "Seattle (Downtown)",
      "Georgetown",
      "Des Moines",
      "Central District",
      "Capitol Hill",
      "Midway",
      "Delridge",
      "SODO"
   ],
   "Bridle Trails":[
      "Bellevue (Downtown)"
   ],
   "Cottage Lake":[
      "Woodinville",
      "Redmond",
      "Duvall",
      "Overlake",
      "Bellevue (Downtown)",
      "Bothell",
      "Avondale",
      "English Hill"
   ],
   "Issaquah":[
      "Bellevue (East)",
      "Snoqualmie",
      "Sammamish",
      "Redmond",
      "University District",
      "Seattle (Downtown)",
      "Eastgate",
      "Beaux Arts",
      "Overlake",
      "Bellevue (Downtown)",
      "North Bend",
      "Montlake",
      "Preston",
      "Clyde Hill",
      "Fall City",
      "Central District",
      "Northgate",
      "Medina",
      "Factoria",
      "First Hill",
      "Mercer Island"
   ],
   "Arbor Heights":[
      "Fauntleroy",
      "Delridge",
      "West Seattle Junction",
      "Gatewood",
      "White Center",
      "SODO",
      "Seattle (Downtown)"
   ],
   "Factoria":[
      "Overlake",
      "Kirkland",
      "Houghton",
      "Montlake",
      "Rose Hill",
      "Renton Highlands",
      "Seattle (Downtown)",
      "Beaux Arts",
      "Bellevue (Downtown)",
      "Eastgate",
      "Renton Boeing",
      "Northgate",
      "Redmond",
      "Renton",
      "Clyde Hill",
      "Newport Hills",
      "Crossroads",
      "Issaquah",
      "Medina",
      "Bellevue (East)"
   ],
   "Kent East Hill":[
      "Timberlane",
      "Renton",
      "Kent",
      "Maple Valley",
      "Lake Meridian",
      "Seattle (Downtown)",
      "Kent Boeing",
      "Covington",
      "Auburn",
      "Tukwila",
      "Midway"
   ],
   "Medina":[
      "Houghton",
      "SODO",
      "Kingsgate",
      "Overlake",
      "University District",
      "Beaux Arts",
      "Renton",
      "Seattle (Downtown)",
      "Rose Hill",
      "Kirkland",
      "Montlake",
      "Ravenna",
      "Totem Lake",
      "Maple Leaf",
      "Redmond",
      "Jackson Park",
      "Finn Hill",
      "Woodinville",
      "Northgate",
      "Lake City",
      "Bellevue (East)",
      "Eastgate",
      "Bitter Lake",
      "North City",
      "Wedgwood",
      "Bellevue (Downtown)",
      "Juanita",
      "Kennydale",
      "Issaquah",
      "Green Lake",
      "Tukwila",
      "Newport Hills",
      "Factoria",
      "South Kirkland",
      "Clyde Hill",
      "Shoreline"
   ],
   "Algona":[
      "Auburn"
   ],
   "Skyway":[
      "Beacon Hill",
      "Rainier Beach",
      "Bryn Mawr",
      "Georgetown",
      "Bothell",
      "SODO",
      "Renton",
      "Seattle (Downtown)",
      "Holly Park"
   ],
   "Black Diamond":[
      "Seattle (Downtown)",
      "Maple Valley",
      "Renton"
   ],
   "Sea-Tac Airport":[
      "Sea-Tac",
      "Star Lake",
      "Renton",
      "Kent",
      "Newport Hills",
      "Beaux Arts",
      "White Center",
      "Midway",
      "Federal Way",
      "Kennydale",
      "Delridge",
      "Bellevue (Downtown)",
      "Burien",
      "Renton Boeing"
   ],
   "Ballard":[
      "Crown Hill",
      "Fremont",
      "Seattle (Downtown)",
      "South Lake Union",
      "Magnolia",
      "Blue Ridge",
      "Phinney Ridge",
      "Greenwood",
      "Broadview",
      "Wedgwood",
      "Queen Anne",
      "Loyal Heights",
      "North Beach",
      "Montlake",
      "Twin Lakes",
      "Bitter Lake",
      "University District",
      "Northgate",
      "Wallingford"
   ],
   "Central District":[
      "Tukwila",
      "Federal Way",
      "Seattle (Downtown)",
      "Northgate",
      "Loyal Heights",
      "Madison Park",
      "Montlake",
      "Columbia City",
      "Lake City",
      "Richmond Highlands",
      "Georgetown",
      "Queen Anne",
      "Eastgate",
      "Capitol Hill",
      "University District",
      "Star Lake",
      "First Hill",
      "Madrona",
      "Kent",
      "Crown Hill",
      "Ravenna",
      "White Center",
      "Midway",
      "Delridge",
      "Wedgwood",
      "Greenwood",
      "South Lake Union",
      "Beacon Hill",
      "North Beach",
      "Mercer Island",
      "Jackson Park",
      "Issaquah",
      "Duwamish Boeing",
      "Green Lake",
      "Mount Baker",
      "Shoreline",
      "Holly Park",
      "Rainier Beach",
      "Rainier Valley",
      "Bitter Lake"
   ],
   "University District":[
      "Maple Leaf",
      "Medina",
      "Loyal Heights",
      "Kirkland",
      "Wallingford",
      "Star Lake",
      "Jackson Park",
      "Crown Hill",
      "Northgate",
      "Kingsgate",
      "Totem Lake",
      "Lake City",
      "Bellevue (East)",
      "Overlake",
      "Midway",
      "Beaux Arts",
      "Rose Hill",
      "Wedgwood",
      "Eastgate",
      "Issaquah",
      "Houghton",
      "Central District",
      "Montlake",
      "Greenwood",
      "Phinney Ridge",
      "Shoreline",
      "Bellevue (Downtown)",
      "South Kirkland",
      "Federal Way",
      "Eastlake",
      "Kent",
      "Rainier Valley",
      "Renton",
      "Twin Lakes",
      "Kennydale",
      "Juanita",
      "Lake Forest Park",
      "Newport Hills",
      "Richmond Highlands",
      "Capitol Hill",
      "Redmond",
      "Queen Anne",
      "First Hill",
      "Seattle (Downtown)",
      "Green Lake",
      "Fremont",
      "Kenmore",
      "Ballard",
      "North Beach",
      "Ravenna",
      "Mount Baker",
      "Clyde Hill",
      "South Lake Union",
      "Innis Arden",
      "Magnolia",
      "Woodinville",
      "Bothell",
      "Sand Point",
      "Mercer Island"
   ],
   "Midway":[
      "University District",
      "Timberlane",
      "Burien",
      "Twin Lakes",
      "Star Lake",
      "Central District",
      "Des Moines",
      "Seattle (Downtown)",
      "Sea-Tac Airport",
      "Lake Meridian",
      "Kent East Hill",
      "Kent",
      "Georgetown",
      "Covington",
      "Duwamish Boeing",
      "Tukwila",
      "First Hill",
      "Federal Way"
   ],
   "North Beach":[
      "Fremont",
      "Green Lake",
      "Lake City",
      "Rainier Valley",
      "Northgate",
      "Loyal Heights",
      "Seattle (Downtown)",
      "Queen Anne",
      "Central District",
      "Greenwood",
      "Crown Hill",
      "Ballard",
      "South Lake Union",
      "Sand Point",
      "Mount Baker",
      "University District",
      "Montlake"
   ],
   "Lake Forest Park":[
      "Totem Lake",
      "Jackson Park",
      "Richmond Highlands",
      "Ravenna",
      "Newport Hills",
      "Bothell",
      "Wedgwood",
      "Kingsgate",
      "Maple Leaf",
      "Houghton",
      "First Hill",
      "Kirkland",
      "Kenmore",
      "South Lake Union",
      "Kennydale",
      "Renton Boeing",
      "Shoreline",
      "University District",
      "Innis Arden",
      "Woodinville",
      "Bellevue (Downtown)",
      "Lake City",
      "Renton",
      "Seattle (Downtown)",
      "Southcenter"
   ],
   "Beaux Arts":[
      "Seattle (Downtown)",
      "Mercer Island",
      "Renton",
      "Northgate",
      "Eastgate",
      "Medina",
      "Renton Boeing",
      "Factoria",
      "White Center",
      "Bellevue (Downtown)",
      "University District",
      "Delridge",
      "Newport Hills",
      "Renton Highlands",
      "Issaquah",
      "Sea-Tac Airport",
      "Sea-Tac",
      "Montlake",
      "Burien",
      "Kennydale"
   ],
   "Holly Park":[
      "Rainier Beach",
      "South Lake Union",
      "SODO",
      "Renton",
      "Capitol Hill",
      "Rainier Valley",
      "Georgetown",
      "Queen Anne",
      "Skyway",
      "Central District",
      "Beacon Hill",
      "Bothell",
      "Seattle (Downtown)"
   ],
   "Maple Leaf":[
      "University District",
      "Overlake",
      "Lake Forest Park",
      "Montlake",
      "Medina",
      "South Lake Union",
      "Woodinville",
      "Seattle (Downtown)",
      "Eastlake",
      "Jackson Park",
      "Bothell",
      "Ravenna",
      "Lake City",
      "Wedgwood",
      "Richmond Highlands",
      "Shoreline",
      "North City",
      "Northgate",
      "Kenmore",
      "Bellevue (Downtown)",
      "Green Lake",
      "Clyde Hill"
   ],
   "Mercer Island":[
      "Beaux Arts",
      "Bellevue (Downtown)",
      "Sammamish",
      "Redmond",
      "Wedgwood",
      "Seattle (Downtown)",
      "Bitter Lake",
      "Central District",
      "First Hill",
      "Issaquah",
      "Kirkland",
      "South Kirkland",
      "Eastgate",
      "University District"
   ],
   "Overlake":[
      "Factoria",
      "Renton Boeing",
      "Northgate",
      "Medina",
      "Maple Leaf",
      "Kingsgate",
      "Bellevue (East)",
      "Sammamish",
      "Redmond",
      "Cottage Lake",
      "Crossroads",
      "Houghton",
      "University District",
      "Finn Hill",
      "Wedgwood",
      "North City",
      "Issaquah",
      "Totem Lake",
      "Shoreline",
      "Kirkland",
      "Eastgate",
      "Renton",
      "Jackson Park",
      "Bitter Lake",
      "South Kirkland",
      "Kent",
      "Auburn",
      "Seattle (Downtown)",
      "Duvall",
      "Avondale",
      "Kenmore",
      "Rose Hill",
      "Bellevue (Downtown)",
      "Montlake",
      "Green Lake"
   ],
   "Alki":[
      "SODO",
      "Rainier Valley",
      "Seattle (Downtown)",
      "Beacon Hill",
      "West Seattle Junction",
      "Admiral District",
      "Delridge",
      "Columbia City"
   ],
   "Eastgate":[
      "Redmond",
      "Sammamish",
      "Renton",
      "Beaux Arts",
      "Renton Boeing",
      "Bellevue (East)",
      "Central District",
      "Factoria",
      "Wedgwood",
      "Northgate",
      "Education Hill",
      "Renton Highlands",
      "University District",
      "Issaquah",
      "Montlake",
      "South Kirkland",
      "Overlake",
      "Kirkland",
      "North Bend",
      "First Hill",
      "Bitter Lake",
      "Houghton",
      "Rose Hill",
      "Medina",
      "Newport Hills",
      "Seattle (Downtown)",
      "Clyde Hill",
      "Snoqualmie",
      "Crossroads",
      "Mercer Island",
      "Bellevue (Downtown)"
   ],
   "Maple Valley":[
      "Renton",
      "Covington",
      "Kent East Hill",
      "Seattle (Downtown)",
      "Timberlane",
      "Lake Meridian",
      "Kent",
      "Black Diamond"
   ],
   "Preston":[
      "Snoqualmie",
      "North Bend",
      "Issaquah",
      "Fall City"
   ],
   "Auburn":[
      "Kirkland",
      "Redmond",
      "Federal Way",
      "Renton Boeing",
      "Totem Lake",
      "Houghton",
      "Lake Meridian",
      "Burien",
      "Muckleshoot Reservation",
      "Newport Hills",
      "Kingsgate",
      "Kent East Hill",
      "Bellevue (Downtown)",
      "Twin Lakes",
      "Star Lake",
      "Sea-Tac",
      "Kent Boeing",
      "Algona",
      "Overlake",
      "Renton",
      "Seattle (Downtown)",
      "SODO",
      "Kent",
      "Kennydale",
      "Enumclaw"
   ],
   "Ravenna":[
      "Lake Forest Park",
      "South Lake Union",
      "Eastlake",
      "Seattle (Downtown)",
      "Clyde Hill",
      "Lake City",
      "Wedgwood",
      "Woodinville",
      "Medina",
      "Northgate",
      "Sand Point",
      "Kenmore",
      "Central District",
      "Green Lake",
      "Maple Leaf",
      "Bothell",
      "Bellevue (Downtown)",
      "First Hill",
      "Montlake",
      "University District",
      "Jackson Park"
   ],
   "Mount Baker":[
      "Wedgwood",
      "Green Lake",
      "Montlake",
      "Loyal Heights",
      "Rainier Beach",
      "Rainier Valley",
      "Madrona",
      "Crown Hill",
      "Greenwood",
      "Bitter Lake",
      "Central District",
      "North Beach",
      "First Hill",
      "University District",
      "Seattle (Downtown)"
   ],
   "Montlake":[
      "Phinney Ridge",
      "Jackson Park",
      "Tukwila",
      "Central District",
      "Mount Baker",
      "Factoria",
      "Redmond",
      "Greenwood",
      "Shoreline",
      "Newport Hills",
      "Seattle (Downtown)",
      "Maple Leaf",
      "Kirkland",
      "Rainier Valley",
      "South Lake Union",
      "Medina",
      "Rose Hill",
      "North City",
      "Bitter Lake",
      "Eastgate",
      "Eastlake",
      "University District",
      "SODO",
      "Beaux Arts",
      "Kennydale",
      "Capitol Hill",
      "Issaquah",
      "Renton",
      "Wallingford",
      "Bellevue (East)",
      "Kingsgate",
      "Totem Lake",
      "Houghton",
      "Finn Hill",
      "Woodinville",
      "Wedgwood",
      "Northgate",
      "Ballard",
      "Green Lake",
      "South Kirkland",
      "Loyal Heights",
      "Clyde Hill",
      "Overlake",
      "Crown Hill",
      "Juanita",
      "Lake City",
      "Ravenna",
      "Bellevue (Downtown)",
      "North Beach"
   ],
   "South Lake Union":[
      "Jackson Park",
      "Phinney Ridge",
      "Greenwood",
      "Richmond Highlands",
      "Twin Lakes",
      "Fremont",
      "Ravenna",
      "Wedgwood",
      "Queen Anne",
      "Ballard",
      "Rainier Beach",
      "Madrona",
      "Innis Arden",
      "Holly Park",
      "Montlake",
      "Kenmore",
      "Maple Leaf",
      "Lake City",
      "Northgate",
      "Shoreline",
      "Blue Ridge",
      "Wallingford",
      "First Hill",
      "Seattle (Downtown)",
      "Lake Forest Park",
      "Loyal Heights",
      "Crown Hill",
      "Bitter Lake",
      "Broadview",
      "Central District",
      "Rainier Valley",
      "Eastlake",
      "Capitol Hill",
      "North Beach",
      "University District",
      "Green Lake"
   ],
   "Broadview":[
      "Queen Anne",
      "Fremont",
      "Seattle (Downtown)",
      "Greenwood",
      "Ballard",
      "Shoreline",
      "South Lake Union",
      "Crown Hill",
      "Blue Ridge",
      "Jackson Park",
      "Bitter Lake",
      "Phinney Ridge",
      "Innis Arden",
      "Richmond Beach",
      "Northgate",
      "Richmond Highlands"
   ],
   "Snoqualmie":[
      "Preston",
      "Issaquah",
      "North Bend",
      "Bellevue (Downtown)",
      "Fall City",
      "Eastgate",
      "Seattle (Downtown)"
   ],
   "Bothell":[
      "Redmond",
      "Houghton",
      "SODO",
      "Shoreline",
      "Totem Lake",
      "Lake Forest Park",
      "Kenmore",
      "Burien",
      "Avondale",
      "White Center",
      "Beacon Hill",
      "Seattle (Downtown)",
      "Richmond Highlands",
      "Delridge",
      "Renton",
      "Skyway",
      "Kennydale",
      "Kirkland",
      "Cottage Lake",
      "Rainier Beach",
      "Maple Leaf",
      "Rose Hill",
      "Bellevue (Downtown)",
      "Wedgwood",
      "Renton Highlands",
      "Newport Hills",
      "Ravenna",
      "English Hill",
      "Georgetown",
      "Lake City",
      "Juanita",
      "Woodinville",
      "Kingsgate",
      "Finn Hill",
      "Holly Park",
      "University District",
      "Renton Boeing"
   ],
   "Georgetown":[
      "Seattle (Downtown)",
      "Des Moines",
      "Kent",
      "Capitol Hill",
      "Central District",
      "Skyway",
      "Federal Way",
      "Rainier Beach",
      "Normandy Park",
      "Duwamish Boeing",
      "Tukwila",
      "Delridge",
      "Bothell",
      "First Hill",
      "White Center",
      "Holly Park",
      "Riverton Heights",
      "Midway",
      "SODO",
      "Burien",
      "Renton",
      "Star Lake",
      "Beacon Hill"
   ],
   "Shoreline":[
      "First Hill",
      "Kenmore",
      "Kirkland",
      "Bothell",
      "Phinney Ridge",
      "Montlake",
      "North City",
      "Seattle (Downtown)",
      "SODO",
      "Houghton",
      "Newport Hills",
      "Innis Arden",
      "Richmond Highlands",
      "Renton",
      "South Lake Union",
      "Jackson Park",
      "Fremont",
      "Overlake",
      "Richmond Beach",
      "Lake City",
      "University District",
      "Renton Boeing",
      "Broadview",
      "Maple Leaf",
      "Lake Forest Park",
      "Bitter Lake",
      "Greenwood",
      "Kennydale",
      "Northgate",
      "Kingsgate",
      "Central District",
      "Totem Lake",
      "Bellevue (Downtown)",
      "Medina",
      "Green Lake"
   ],
   "Vashon Island":[
      "Seattle (Downtown)",
      "Fauntleroy",
      "SODO",
      "Gatewood"
   ],
   "Northgate":[
      "First Hill",
      "Beaux Arts",
      "Central District",
      "Overlake",
      "Fremont",
      "Seattle (Downtown)",
      "North City",
      "Lake City",
      "Wedgwood",
      "University District",
      "Sand Point",
      "Eastgate",
      "Bitter Lake",
      "Richmond Highlands",
      "North Beach",
      "Ravenna",
      "South Lake Union",
      "Medina",
      "Factoria",
      "Queen Anne",
      "Wallingford",
      "Richmond Beach",
      "Maple Leaf",
      "Montlake",
      "Green Lake",
      "Issaquah",
      "Jackson Park",
      "Innis Arden",
      "Shoreline",
      "Loyal Heights",
      "Eastlake",
      "Crown Hill",
      "Broadview",
      "Ballard",
      "Bellevue (Downtown)"
   ],
   "Bitter Lake":[
      "Capitol Hill",
      "Blue Ridge",
      "Seattle (Downtown)",
      "Innis Arden",
      "Jackson Park",
      "Madison Park",
      "Kirkland",
      "Rainier Valley",
      "Northgate",
      "South Kirkland",
      "Houghton",
      "Montlake",
      "Richmond Highlands",
      "Green Lake",
      "First Hill",
      "Magnolia",
      "Eastgate",
      "Mercer Island",
      "South Lake Union",
      "Sand Point",
      "Medina",
      "Crown Hill",
      "Overlake",
      "Queen Anne",
      "Madrona",
      "Greenwood",
      "Fremont",
      "Shoreline",
      "Richmond Beach",
      "Wedgwood",
      "Broadview",
      "Mount Baker",
      "Phinney Ridge",
      "Ballard",
      "Bellevue (Downtown)",
      "Central District",
      "Rainier Beach"
   ],
   "Columbia City":[
      "SODO",
      "Rainier Valley",
      "Central District",
      "First Hill",
      "Admiral District",
      "Rainier Beach",
      "Beacon Hill",
      "Capitol Hill",
      "Seattle (Downtown)",
      "West Seattle Junction",
      "Alki"
   ],
   "Star Lake":[
      "Tukwila",
      "First Hill",
      "Sea-Tac Airport",
      "Twin Lakes",
      "Seattle (Downtown)",
      "University District",
      "Duwamish Boeing",
      "Central District",
      "Auburn",
      "Midway",
      "Kent",
      "SODO",
      "Federal Way",
      "Des Moines",
      "Georgetown"
   ],
   "McMicken Heights":[
      "Southcenter",
      "Sea-Tac",
      "Tukwila",
      "Des Moines"
   ],
   "Federal Way":[
      "Central District",
      "Tukwila",
      "Auburn",
      "Sea-Tac",
      "Twin Lakes",
      "Georgetown",
      "Duwamish Boeing",
      "SODO",
      "University District",
      "First Hill",
      "Seattle (Downtown)",
      "Sea-Tac Airport",
      "Kent",
      "Northeast Tacoma",
      "Star Lake",
      "Des Moines",
      "Midway"
   ],
   "Clyde Hill":[
      "Jackson Park",
      "Lake City",
      "Ravenna",
      "Kennydale",
      "Renton",
      "Tukwila",
      "Wedgwood",
      "Seattle (Downtown)",
      "SODO",
      "Factoria",
      "Bellevue (Downtown)",
      "Issaquah",
      "Eastgate",
      "Bellevue (East)",
      "Newport Hills",
      "Montlake",
      "Medina",
      "Maple Leaf",
      "University District"
   ],
   "Crossroads":[
      "Rose Hill",
      "Redmond",
      "Overlake",
      "Houghton",
      "Bellevue (East)",
      "Factoria",
      "Kirkland",
      "Eastgate",
      "Education Hill",
      "Bellevue (Downtown)"
   ],
   "Juanita":[
      "Kirkland",
      "Rose Hill",
      "Kingsgate",
      "Totem Lake",
      "Bellevue (Downtown)",
      "Seattle (Downtown)",
      "Kenmore",
      "University District",
      "Medina",
      "Woodinville",
      "South Kirkland",
      "Bothell",
      "Houghton",
      "Montlake",
      "Finn Hill"
   ],
   "Kingsgate":[
      "Woodinville",
      "South Kirkland",
      "Totem Lake",
      "Medina",
      "Kennydale",
      "Overlake",
      "Richmond Highlands",
      "University District",
      "Lake Forest Park",
      "Juanita",
      "Renton",
      "Rose Hill",
      "Auburn",
      "Kent",
      "Houghton",
      "Bellevue (Downtown)",
      "Montlake",
      "Seattle (Downtown)",
      "Renton Boeing",
      "Newport Hills",
      "Redmond",
      "Shoreline",
      "Kenmore",
      "Bothell",
      "Kirkland",
      "Finn Hill"
   ],
   "Normandy Park":[
      "Georgetown",
      "Burien",
      "Des Moines",
      "Seattle (Downtown)"
   ],
   "Richmond Highlands":[
      "Greenwood",
      "South Lake Union",
      "Houghton",
      "Lake Forest Park",
      "Totem Lake",
      "Kingsgate",
      "Central District",
      "Bellevue (Downtown)",
      "Renton Boeing",
      "Newport Hills",
      "Innis Arden",
      "Bothell",
      "Richmond Beach",
      "Northgate",
      "Bitter Lake",
      "Shoreline",
      "Phinney Ridge",
      "Renton",
      "Kenmore",
      "Kirkland",
      "Maple Leaf",
      "Kennydale",
      "Seattle (Downtown)",
      "Jackson Park",
      "First Hill",
      "University District",
      "Green Lake",
      "SODO",
      "North City",
      "Broadview"
   ],
   "Finn Hill":[
      "Redmond",
      "Seattle (Downtown)",
      "South Kirkland",
      "Overlake",
      "Rose Hill",
      "Medina",
      "Totem Lake",
      "Kenmore",
      "Montlake",
      "Kirkland",
      "Bellevue (Downtown)",
      "Bothell",
      "Houghton",
      "Kingsgate",
      "Juanita"
   ],
   "Wallingford":[
      "Fremont",
      "Magnolia",
      "Seattle (Downtown)",
      "Queen Anne",
      "University District",
      "Green Lake",
      "Greenwood",
      "South Lake Union",
      "Montlake",
      "Northgate",
      "Phinney Ridge",
      "Ballard"
   ],
   "Bellevue (Downtown)":[
      "Renton Boeing",
      "Duvall",
      "Totem Lake",
      "Education Hill",
      "Renton",
      "Redmond",
      "Newport Hills",
      "Kennydale",
      "Rose Hill",
      "North Bend",
      "Richmond Highlands",
      "Kent",
      "Factoria",
      "Snoqualmie",
      "Beaux Arts",
      "Mercer Island",
      "Bridle Trails",
      "Houghton",
      "Renton Highlands",
      "Avondale",
      "White Center",
      "Sea-Tac",
      "Bellevue (East)",
      "Cottage Lake",
      "Kirkland",
      "Issaquah",
      "Auburn",
      "Burien",
      "SODO",
      "University District",
      "Seattle (Downtown)",
      "Kingsgate",
      "Kenmore",
      "Bothell",
      "Juanita",
      "Ravenna",
      "Clyde Hill",
      "Medina",
      "Sammamish",
      "Sea-Tac Airport",
      "Jackson Park",
      "Maple Leaf",
      "Lake City",
      "Woodinville",
      "Lake Forest Park",
      "Finn Hill",
      "Overlake",
      "Delridge",
      "Wedgwood",
      "Tukwila",
      "South Kirkland",
      "Eastgate",
      "Montlake",
      "Bitter Lake",
      "Shoreline",
      "Crossroads",
      "Northgate"
   ],
   "Sand Point":[
      "Seattle (Downtown)",
      "Lake City",
      "Northgate",
      "Ravenna",
      "Loyal Heights",
      "Bitter Lake",
      "Wedgwood",
      "North Beach",
      "University District"
   ],
   "Des Moines":[
      "Georgetown",
      "Burien",
      "Kent",
      "Sea-Tac",
      "Southcenter",
      "McMicken Heights",
      "Midway",
      "Duwamish Boeing",
      "Seattle (Downtown)",
      "Star Lake",
      "Normandy Park",
      "Tukwila",
      "Federal Way"
   ],
   "Southcenter":[
      "McMicken Heights",
      "Fauntleroy",
      "Riverton Heights",
      "White Center",
      "Kenmore",
      "Lake City",
      "Seattle (Downtown)",
      "SODO",
      "Burien",
      "Tukwila",
      "Delridge",
      "Gatewood",
      "Des Moines",
      "Sea-Tac",
      "Kent Boeing",
      "Admiral District",
      "Renton Boeing",
      "Fairwood",
      "Kent",
      "Renton",
      "West Seattle Junction",
      "Lake Forest Park"
   ],
   "Burien":[
      "SODO",
      "Renton",
      "White Center",
      "Riverton Heights",
      "Bothell",
      "Des Moines",
      "Kennydale",
      "Southcenter",
      "Kent",
      "Kent Boeing",
      "Auburn",
      "Newport Hills",
      "Midway",
      "Bellevue (Downtown)",
      "Delridge",
      "Renton Boeing",
      "Beaux Arts",
      "Tukwila",
      "Georgetown",
      "Seattle (Downtown)",
      "Normandy Park",
      "Sea-Tac",
      "Sea-Tac Airport"
   ]
}