var NeighborPairDict = {
   "Jackson Park/South Lake Union":"853",
   "Bellevue (Downtown)/Renton Boeing":"1064",
   "Kenmore/Totem Lake":"199",
   "Lake Forest Park/Totem Lake":"208",
   "Montlake/Phinney Ridge":"528",
   "Avondale/Rose Hill":"739",
   "Duwamish Boeing/White Center":"16",
   "Des Moines/Duwamish Boeing":"959",
   "Duwamish Boeing/Riverton Heights":"407",
   "Beaux Arts/Bellevue (Downtown)":"1191",
   "Houghton/Kirkland":"166",
   "Madison Park/Wedgwood":"335",
   "Beaux Arts/University District":"1112",
   "Kingsgate/Woodinville":"903",
   "Bellevue (Downtown)/Duvall":"1169",
   "Kennydale/Renton":"119",
   "Sand Point/Seattle (Downtown)":"799",
   "Factoria/Overlake":"232",
   "Houghton/Medina":"806",
   "Des Moines/Georgetown":"1151",
   "Juanita/Kirkland":"183",
   "Beacon Hill/SODO":"350",
   "Houghton/Redmond":"254",
   "Fauntleroy/Southcenter":"737",
   "Fremont/North Beach":"319",
   "Greenwood/North Beach":"441",
   "Finn Hill/Redmond":"271",
   "Bothell/Juanita":"1145",
   "Auburn/Kirkland":"162",
   "Central District/Columbia City":"1039",
   "Kirkland/Redmond":"158",
   "Fremont/Greenwood":"309",
   "Fremont/Wallingford":"326",
   "Avondale/Redmond":"252",
   "Finn Hill/Montlake":"1129",
   "Medina/Montlake":"991",
   "Green Lake/Medina":"879",
   "Bellevue (East)/Issaquah":"44",
   "Delridge/Renton Boeing":"510",
   "Central District/First Hill":"828",
   "Wedgwood/Woodinville":"893",
   "Star Lake/Tukwila":"464",
   "Columbia City/Seattle (Downtown)":"791",
   "Eastgate/Redmond":"264",
   "Cottage Lake/Redmond":"258",
   "Northgate/Sand Point":"1165",
   "Kennydale/Totem Lake":"197",
   "SODO/West Seattle Junction":"351",
   "Renton/SODO":"118",
   "Auburn/Redmond":"250",
   "Central District/Tukwila":"473",
   "Beaux Arts/Renton":"155",
   "Columbia City/Rainier Valley":"567",
   "Rainier Beach/Rainier Valley":"413",
   "Tukwila/White Center":"6",
   "Seattle (Downtown)/Wedgwood":"753",
   "Houghton/Renton":"129",
   "Ravenna/Wedgwood":"934",
   "Riverton Heights/Southcenter":"411",
   "First Hill/Northgate":"838",
   "Bellevue (Downtown)/Mercer Island":"1082",
   "Madrona/Wedgwood":"641",
   "Medina/SODO":"355",
   "Phinney Ridge/South Lake Union":"529",
   "Queen Anne/University District":"688",
   "Crown Hill/Fremont":"314",
   "Kingsgate/South Kirkland":"716",
   "Fauntleroy/Riverton Heights":"403",
   "Beaux Arts/Northgate":"1166",
   "Georgetown/Seattle (Downtown)":"785",
   "Central District/Northgate":"1037",
   "Southcenter/White Center":"26",
   "First Hill/Kent":"84",
   "Kenmore/Shoreline":"604",
   "Medina/Ravenna":"990",
   "Greenwood/Wallingford":"449",
   "Bothell/Houghton":"813",
   "Greenwood/South Lake Union":"445",
   "Alki/SODO":"359",
   "First Hill/Star Lake":"648",
   "Factoria/Renton Boeing":"978",
   "Burien/SODO":"364",
   "Federal Way/Tukwila":"479",
   "Green Lake/Ravenna":"885",
   "Magnolia/Wallingford":"955",
   "Crossroads/Rose Hill":"920",
   "Central District/Madison Park":"336",
   "Sea-Tac Airport/Star Lake":"654",
   "Redmond/South Kirkland":"251",
   "Kingsgate/Medina":"997",
   "Burien/Kent Boeing":"375",
   "Richmond Highlands/South Lake Union":"1010",
   "Kirkland/Shoreline":"180",
   "First Hill/South Lake Union":"835",
   "Northgate/Overlake":"240",
   "Mount Baker/Wedgwood":"935",
   "Crown Hill/Phinney Ridge":"522",
   "Georgetown/Kent":"91",
   "Green Lake/North City":"877",
   "Admiral District/SODO":"352",
   "Beacon Hill/Columbia City":"870",
   "Federal Way/University District":"1105",
   "Factoria/Kirkland":"170",
   "Burien/Renton":"148",
   "Preston/Snoqualmie":"1097",
   "Queen Anne/Rainier Valley":"548",
   "Clyde Hill/Seattle (Downtown)":"793",
   "Capitol Hill/Delridge":"500",
   "Bellevue (Downtown)/Redmond":"272",
   "Innis Arden/Seattle (Downtown)":"489",
   "Rainier Valley/Seattle (Downtown)":"551",
   "Bitter Lake/Northgate":"1162",
   "Houghton/Richmond Highlands":"807",
   "Lake Forest Park/Richmond Highlands":"1006",
   "Bothell/SODO":"361",
   "North Bend/Seattle (Downtown)":"453",
   "Beaux Arts/Medina":"1000",
   "Green Lake/Seattle (Downtown)":"749",
   "Rainier Beach/South Lake Union":"424",
   "Beacon Hill/Georgetown":"869",
   "Bitter Lake/Medina":"994",
   "Bellevue (Downtown)/Newport Hills":"588",
   "Medina/Overlake":"233",
   "Kirkland/Woodinville":"167",
   "Clyde Hill/Ravenna":"1117",
   "Green Lake/Mount Baker":"886",
   "North City/Northgate":"910",
   "Montlake/University District":"1100",
   "Central District/South Lake Union":"1034",
   "Southcenter/West Seattle Junction":"948",
   "Kenmore/Seattle (Downtown)":"591",
   "Bitter Lake/Broadview":"1140",
   "Central District/Montlake":"1033",
   "Clyde Hill/Tukwila":"481",
   "Factoria/Houghton":"805",
   "Maple Leaf/Overlake":"235",
   "Seattle (Downtown)/Wallingford":"797",
   "Arbor Heights/Fauntleroy":"735",
   "Kenmore/Lake City":"285",
   "Renton/Sea-Tac Airport":"152",
   "Seattle (Downtown)/Star Lake":"647",
   "Eastgate/Renton":"141",
   "Houghton/Rose Hill":"803",
   "Kennydale/Kingsgate":"397",
   "Lake City/Northgate":"304",
   "Crossroads/Houghton":"816",
   "Magnolia/Queen Anne":"683",
   "Arbor Heights/Delridge":"508",
   "Bellevue (Downtown)/Rose Hill":"924",
   "Bothell/Shoreline":"1143",
   "Delridge/West Seattle Junction":"505",
   "Medina/University District":"989",
   "Cottage Lake/Duvall":"962",
   "Ballard/Fremont":"318",
   "Bellevue (Downtown)/North Bend":"459",
   "Newport Hills/Sea-Tac":"584",
   "Issaquah/Preston":"969",
   "Burien/White Center":"22",
   "Loyal Heights/North Beach":"699",
   "Kirkland/Seattle (Downtown)":"165",
   "Loyal Heights/University District":"700",
   "SODO/Tukwila":"342",
   "Crown Hill/Magnolia":"721",
   "Capitol Hill/Eastlake":"101",
   "Montlake/Mount Baker":"1120",
   "Fremont/South Lake Union":"321",
   "Lake Forest Park/Ravenna":"1050",
   "Kingsgate/Overlake":"244",
   "Bitter Lake/Mount Baker":"1121",
   "Lake Forest Park/Newport Hills":"576",
   "Kent/Twin Lakes":"28",
   "Bellevue (East)/Overlake":"39",
   "Clyde Hill/Jackson Park":"858",
   "Capitol Hill/Georgetown":"621",
   "Broadview/Fremont":"322",
   "Green Lake/North Beach":"882",
   "Ballard/Wallingford":"1025",
   "Ravenna/South Lake Union":"1114",
   "Kennydale/Tukwila":"378",
   "Bellevue (Downtown)/Bridle Trails":"960",
   "Fremont/Innis Arden":"310",
   "Kenmore/Southcenter":"609",
   "Loyal Heights/Northgate":"704",
   "Beacon Hill/Skyway":"864",
   "Overlake/Sammamish":"53",
   "Kingsgate/Richmond Highlands":"1016",
   "Bitter Lake/Shoreline":"1153",
   "First Hill/Seattle (Downtown)":"745",
   "Lake Forest Park/Maple Leaf":"1048",
   "Bothell/Ravenna":"1115",
   "Kirkland/South Kirkland":"163",
   "Clyde Hill/Issaquah":"974",
   "Riverton Heights/White Center":"5",
   "Kirkland/University District":"177",
   "Duvall/Redmond":"268",
   "Northgate/University District":"1104",
   "Queen Anne/Wallingford":"693",
   "Beaux Arts/Sea-Tac":"1180",
   "Northgate/Richmond Highlands":"1014",
   "Georgetown/Skyway":"1003",
   "First Hill/Georgetown":"836",
   "Madrona/South Lake Union":"644",
   "Factoria/Montlake":"980",
   "Montlake/Redmond":"266",
   "Lake City/Southcenter":"308",
   "Sea-Tac/White Center":"23",
   "Finn Hill/South Kirkland":"717",
   "Green Lake/Greenwood":"437",
   "Renton/Sea-Tac":"149",
   "Blue Ridge/Greenwood":"432",
   "Bothell/Totem Lake":"212",
   "Issaquah/Snoqualmie":"972",
   "Auburn/Federal Way":"673",
   "Phinney Ridge/Richmond Highlands":"525",
   "Ravenna/Seattle (Downtown)":"778",
   "Renton/White Center":"1",
   "Phinney Ridge/Shoreline":"531",
   "Newport Hills/Tukwila":"463",
   "Covington/Maple Valley":"66",
   "Kenmore/Kingsgate":"606",
   "Lake City/North Beach":"295",
   "Kingsgate/Rose Hill":"922",
   "Seattle (Downtown)/South Kirkland":"706",
   "Houghton/Seattle (Downtown)":"744",
   "Auburn/Renton Boeing":"671",
   "Juanita/Rose Hill":"921",
   "Bothell/Richmond Highlands":"1012",
   "South Lake Union/Twin Lakes":"36",
   "Kennydale/Renton Boeing":"389",
   "Kent/Sea-Tac":"94",
   "Bitter Lake/Richmond Beach":"663",
   "Kent/Sea-Tac Airport":"96",
   "South Lake Union/Wedgwood":"937",
   "Star Lake/University District":"651",
   "Overlake/Redmond":"218",
   "Finn Hill/Houghton":"819",
   "Central District/Richmond Highlands":"1005",
   "Auburn/Kent East Hill":"669",
   "Crossroads/Redmond":"269",
   "Ballard/Bitter Lake":"1024",
   "Sea-Tac/Sea-Tac Airport":"1176",
   "Greenwood/Montlake":"444",
   "Cottage Lake/Overlake":"230",
   "Newport Hills/Sea-Tac Airport":"587",
   "Seattle (Downtown)/White Center":"11",
   "West Seattle Junction/White Center":"14",
   "Capitol Hill/First Hill":"613",
   "Kent East Hill/Renton":"133",
   "Crossroads/Overlake":"243",
   "Renton Boeing/Totem Lake":"209",
   "English Hill/Woodinville":"625",
   "Bothell/Kenmore":"603",
   "Burien/Riverton Heights":"410",
   "Capitol Hill/Queen Anne":"611",
   "Clyde Hill/Kennydale":"396",
   "Rainier Beach/Skyway":"420",
   "Redmond/Totem Lake":"196",
   "Burien/Normandy Park":"1085",
   "Gatewood/Tukwila":"275",
   "Holly Park/South Lake Union":"1067",
   "Capitol Hill/Madrona":"610",
   "Jackson Park/University District":"850",
   "Factoria/Renton Highlands":"871",
   "Factoria/Seattle (Downtown)":"760",
   "Houghton/Overlake":"224",
   "North Bend/Snoqualmie":"458",
   "Crown Hill/University District":"725",
   "Medina/Renton":"134",
   "Bothell/Burien":"1144",
   "Alki/Rainier Valley":"561",
   "Avondale/Duvall":"742",
   "Burien/Des Moines":"1159",
   "Bitter Lake/Seattle (Downtown)":"790",
   "First Hill/Lake City":"288",
   "Des Moines/Kent":"98",
   "Kent/Kent East Hill":"86",
   "Bellevue (East)/Eastgate":"47",
   "Avondale/Bellevue (Downtown)":"743",
   "Bellevue (Downtown)/Sea-Tac":"1177",
   "Eastgate/Montlake":"1089",
   "Montlake/Shoreline":"1123",
   "Ballard/Seattle (Downtown)":"766",
   "Bitter Lake/Capitol Hill":"622",
   "Admiral District/Gatewood":"280",
   "Innis Arden/Lake City":"284",
   "Bellevue (Downtown)/Kent":"97",
   "Auburn/Totem Lake":"200",
   "Shoreline/South Lake Union":"1134",
   "Montlake/North City":"908",
   "Lake Forest Park/South Lake Union":"1051",
   "Montlake/Rainier Valley":"564",
   "Eastgate/South Kirkland":"711",
   "Avondale/Bothell":"741",
   "Alki/Seattle (Downtown)":"774",
   "Kennydale/Seattle (Downtown)":"383",
   "Jackson Park/Northgate":"856",
   "Kent East Hill/Maple Valley":"986",
   "Beaux Arts/Renton Boeing":"1066",
   "Bitter Lake/South Lake Union":"1136",
   "Holly Park/Rainier Beach":"422",
   "Bothell/White Center":"20",
   "Broadview/Seattle (Downtown)":"782",
   "Kent/SODO":"73",
   "Duwamish Boeing/Star Lake":"649",
   "Kingsgate/Lake Forest Park":"1054",
   "Des Moines/Sea-Tac":"1178",
   "Greenwood/Rainier Valley":"431",
   "Rainier Valley/SODO":"344",
   "Covington/Seattle (Downtown)":"64",
   "Central District/Kent":"87",
   "Seattle (Downtown)/Southcenter":"801",
   "Montlake/Newport Hills":"580",
   "Lake City/University District":"298",
   "Bellevue (Downtown)/Richmond Highlands":"1017",
   "North City/Shoreline":"909",
   "Kenmore/Woodinville":"594",
   "Kent/Seattle (Downtown)":"82",
   "Bitter Lake/Sand Point":"1168",
   "Kent East Hill/Seattle (Downtown)":"761",
   "Bitter Lake/Innis Arden":"498",
   "Medina/Rose Hill":"915",
   "Renton Highlands/Seattle (Downtown)":"748",
   "Beaux Arts/Factoria":"985",
   "Bellevue (Downtown)/Factoria":"984",
   "Crown Hill/Montlake":"727",
   "Eastlake/Seattle (Downtown)":"102",
   "Bellevue (East)/University District":"48",
   "Beacon Hill/First Hill":"822",
   "Green Lake/Wallingford":"892",
   "Lake Meridian/Seattle (Downtown)":"192",
   "Bryn Mawr/Skyway":"460",
   "Delridge/Renton":"124",
   "Renton Boeing/White Center":"19",
   "Montlake/Seattle (Downtown)":"780",
   "Broadview/Greenwood":"446",
   "Crown Hill/North Beach":"724",
   "Capitol Hill/Rainier Valley":"547",
   "Green Lake/Jackson Park":"842",
   "Bellevue (Downtown)/Totem Lake":"217",
   "Kirkland/Montlake":"178",
   "SODO/Southcenter":"370",
   "Covington/Timberlane":"63",
   "Newport Hills/Richmond Highlands":"575",
   "Auburn/Houghton":"668",
   "Overlake/University District":"237",
   "Admiral District/West Seattle Junction":"944",
   "Kennydale/Renton Highlands":"385",
   "Bothell/Kingsgate":"1146",
   "Federal Way/Sea-Tac":"1173",
   "Juanita/Kingsgate":"1183",
   "Kent/Redmond":"72",
   "Houghton/Lake Forest Park":"808",
   "Montlake/Wedgwood":"936",
   "Central District/Georgetown":"1035",
   "Lake City/Ravenna":"299",
   "Richmond Beach/Seattle (Downtown)":"656",
   "Burien/Kennydale":"394",
   "Beacon Hill/Duwamish Boeing":"863",
   "Kingsgate/Renton":"151",
   "Kent East Hill/Lake Meridian":"193",
   "Georgetown/SODO":"362",
   "Innis Arden/Richmond Highlands":"491",
   "Beaux Arts/White Center":"27",
   "Fairwood/SODO":"327",
   "Innis Arden/Phinney Ridge":"486",
   "Fauntleroy/White Center":"10",
   "Fairwood/Renton":"117",
   "Montlake/Northgate":"1124",
   "First Hill/Rainier Valley":"552",
   "Seattle (Downtown)/Shoreline":"786",
   "Kirkland/Medina":"171",
   "SODO/Shoreline":"363",
   "Rainier Beach/SODO":"341",
   "Kent Boeing/Kent East Hill":"374",
   "Ballard/South Lake Union":"1021",
   "Beacon Hill/Bothell":"868",
   "Greenwood/Loyal Heights":"434",
   "Federal Way/Twin Lakes":"37",
   "Bryn Mawr/Renton":"122",
   "Bitter Lake/Madison Park":"337",
   "Kenmore/South Lake Union":"602",
   "Bitter Lake/Kirkland":"181",
   "North Beach/Rainier Valley":"559",
   "Delridge/SODO":"343",
   "Bothell/Seattle (Downtown)":"784",
   "Richmond Highlands/Seattle (Downtown)":"765",
   "Auburn/Lake Meridian":"191",
   "Beacon Hill/Seattle (Downtown)":"747",
   "Lake Meridian/Renton":"112",
   "Kent/Renton":"67",
   "Midway/University District":"541",
   "Ballard/Magnolia":"952",
   "Duwamish Boeing/Federal Way":"958",
   "Central District/Queen Anne":"685",
   "McMicken Heights/Sea-Tac":"1170",
   "Bothell/Delridge":"512",
   "Central District/Eastgate":"1029",
   "Bellevue (Downtown)/Snoqualmie":"1141",
   "Redmond/Sammamish":"54",
   "Ravenna/University District":"1098",
   "Southcenter/Tukwila":"484",
   "North Beach/South Lake Union":"1044",
   "Beaux Arts/Seattle (Downtown)":"802",
   "Admiral District/White Center":"15",
   "Medina/Wedgwood":"926",
   "Rose Hill/University District":"917",
   "Overlake/Renton Boeing":"234",
   "Green Lake/Queen Anne":"681",
   "First Hill/Shoreline":"837",
   "Delridge/Southcenter":"518",
   "Eastgate/Factoria":"979",
   "Central District/Federal Way":"1040",
   "Bothell/Renton":"145",
   "Duwamish Boeing/Tukwila":"470",
   "Eastgate/Wedgwood":"932",
   "Eastgate/Sammamish":"58",
   "Burien/Kent":"92",
   "Star Lake/Twin Lakes":"30",
   "Fall City/Preston":"912",
   "Auburn/Burien":"672",
   "Eastgate/Northgate":"1091",
   "Green Lake/Rainier Valley":"554",
   "Lake City/Sand Point":"307",
   "Bellevue (East)/Houghton":"42",
   "Riverton Heights/SODO":"340",
   "Finn Hill/Rose Hill":"923",
   "Kirkland/Rose Hill":"168",
   "Fremont/Magnolia":"317",
   "Kent/Kirkland":"68",
   "Medina/Seattle (Downtown)":"762",
   "Beacon Hill/Delridge":"504",
   "Eastlake/Ravenna":"107",
   "Richmond Beach/Richmond Highlands":"659",
   "Seattle (Downtown)/Woodinville":"750",
   "Kent Boeing/Seattle (Downtown)":"373",
   "SODO/Seattle (Downtown)":"349",
   "Shoreline/University District":"1103",
   "Maple Valley/Seattle (Downtown)":"776",
   "Ballard/Blue Ridge":"631",
   "Maple Leaf/Shoreline":"1075",
   "Northgate/Wallingford":"1163",
   "Federal Way/Georgetown":"1150",
   "Maple Valley/Timberlane":"637",
   "First Hill/Richmond Highlands":"827",
   "Bitter Lake/Houghton":"815",
   "Clyde Hill/Lake City":"305",
   "Kingsgate/Kirkland":"184",
   "Bothell/Skyway":"1002",
   "Kenmore/Wedgwood":"595",
   "Delridge/Seattle (Downtown)":"502",
   "Houghton/Shoreline":"814",
   "Lake City/Wedgwood":"292",
   "Newport Hills/Shoreline":"582",
   "Fall City/Issaquah":"911",
   "Gatewood/West Seattle Junction":"279",
   "Midway/Timberlane":"534",
   "First Hill/Lake Forest Park":"829",
   "Crown Hill/Greenwood":"435",
   "Montlake/South Lake Union":"1122",
   "English Hill/Redmond":"248",
   "Kenmore/Renton Boeing":"598",
   "Montlake/Rose Hill":"918",
   "University District/Wedgwood":"933",
   "Finn Hill/Overlake":"245",
   "Overlake/Wedgwood":"229",
   "Mercer Island/South Kirkland":"710",
   "Central District/Shoreline":"1036",
   "Renton Boeing/Tukwila":"474",
   "Issaquah/Sammamish":"56",
   "Eastgate/Education Hill":"664",
   "Eastgate/Renton Highlands":"873",
   "Rose Hill/Totem Lake":"205",
   "South Lake Union/Wallingford":"1137",
   "Eastlake/Wedgwood":"104",
   "Covington/Midway":"62",
   "Mercer Island/Redmond":"263",
   "Covington/Lake Meridian":"61",
   "Bellevue (Downtown)/Houghton":"820",
   "Seattle (Downtown)/West Seattle Junction":"754",
   "North Beach/Northgate":"1045",
   "Northgate/Ravenna":"1116",
   "Kent/Renton Boeing":"88",
   "Maple Leaf/University District":"1070",
   "Issaquah/Redmond":"259",
   "Black Diamond/Seattle (Downtown)":"764",
   "Sammamish/Seattle (Downtown)":"55",
   "Beaux Arts/Newport Hills":"589",
   "Auburn/Kent":"81",
   "Capitol Hill/Central District":"616",
   "Maple Leaf/Medina":"987",
   "Innis Arden/Shoreline":"496",
   "Juanita/Totem Lake":"214",
   "Federal Way/SODO":"367",
   "Kirkland/Newport Hills":"160",
   "Loyal Heights/Mount Baker":"701",
   "Kirkland/Lake Forest Park":"173",
   "Kingsgate/University District":"1108",
   "Burien/Newport Hills":"583",
   "Rainier Valley/Wedgwood":"555",
   "First Hill/Green Lake":"823",
   "Lake City/Loyal Heights":"286",
   "Bitter Lake/Montlake":"1125",
   "Gatewood/Southcenter":"283",
   "Beaux Arts/Renton Highlands":"876",
   "Issaquah/University District":"970",
   "Kenmore/Newport Hills":"568",
   "Bellevue (Downtown)/Lake City":"306",
   "Bitter Lake/Richmond Highlands":"1015",
   "Auburn/Bellevue (Downtown)":"676",
   "Issaquah/Seattle (Downtown)":"758",
   "Auburn/Muckleshoot Reservation":"485",
   "Clyde Hill/Montlake":"1126",
   "Bellevue (Downtown)/Renton Highlands":"875",
   "First Hill/Ravenna":"833",
   "North City/Overlake":"227",
   "Beacon Hill/White Center":"13",
   "Eastgate/Issaquah":"968",
   "Auburn/Enumclaw":"452",
   "Bothell/Georgetown":"1142",
   "Bitter Lake/Green Lake":"891",
   "Admiral District/Columbia City":"950",
   "Holly Park/SODO":"358",
   "Des Moines/Southcenter":"1192",
   "Rainier Beach/Seattle (Downtown)":"416",
   "Kirkland/Totem Lake":"156",
   "Bothell/Kennydale":"392",
   "Maple Leaf/South Lake Union":"1073",
   "Duwamish Boeing/Kent":"85",
   "Green Lake/Phinney Ridge":"524",
   "University District/Wallingford":"1109",
   "Green Lake/Lake City":"290",
   "Lake City/South Lake Union":"301",
   "Northgate/South Lake Union":"1135",
   "Broadview/Crown Hill":"729",
   "North Beach/Seattle (Downtown)":"768",
   "Bitter Lake/Blue Ridge":"634",
   "Madrona/Seattle (Downtown)":"639",
   "Renton Boeing/Sea-Tac":"1061",
   "Bothell/Kirkland":"179",
   "Beaux Arts/Issaquah":"976",
   "North City/Richmond Beach":"658",
   "Maple Leaf/Woodinville":"897",
   "Kennydale/University District":"390",
   "Columbia City/Rainier Beach":"428",
   "Fauntleroy/West Seattle Junction":"733",
   "Burien/Midway":"543",
   "Avondale/Overlake":"222",
   "Ballard/Phinney Ridge":"526",
   "Avondale/English Hill":"624",
   "Carnation/Harbor Island":"450",
   "North City/Seattle (Downtown)":"751",
   "Blue Ridge/Broadview":"633",
   "Gatewood/Riverton Heights":"274",
   "Bellevue (Downtown)/White Center":"25",
   "Bitter Lake/Magnolia":"954",
   "Crown Hill/Seattle (Downtown)":"719",
   "Auburn/Newport Hills":"569",
   "Mercer Island/Seattle (Downtown)":"772",
   "Redmond/Renton":"115",
   "Houghton/Totem Lake":"203",
   "Georgetown/Rainier Beach":"426",
   "Jackson Park/Medina":"845",
   "Bellevue (East)/Rose Hill":"43",
   "Delridge/Tukwila":"461",
   "Bellevue (Downtown)/Bellevue (East)":"52",
   "Holly Park/Renton":"140",
   "Northgate/Shoreline":"1152",
   "Bellevue (Downtown)/Medina":"999",
   "Delridge/White Center":"7",
   "Juanita/University District":"1107",
   "Fall City/North Bend":"454",
   "Issaquah/Overlake":"231",
   "SODO/Skyway":"356",
   "Jackson Park/Shoreline":"855",
   "Bellevue (Downtown)/Cottage Lake":"963",
   "Central District/Star Lake":"650",
   "Bellevue (Downtown)/Kirkland":"186",
   "McMicken Heights/Tukwila":"478",
   "Blue Ridge/South Lake Union":"632",
   "Kent/Lake Meridian":"69",
   "Finn Hill/Medina":"998",
   "Renton/Richmond Highlands":"137",
   "Eastgate/Rose Hill":"916",
   "Kent East Hill/Tukwila":"471",
   "Houghton/South Kirkland":"707",
   "Kenmore/Lake Forest Park":"597",
   "Bellevue (Downtown)/Northgate":"1164",
   "Eastlake/Lake City":"100",
   "Sea-Tac/Southcenter":"1179",
   "First Hill/Mercer Island":"830",
   "Newport Hills/Renton":"125",
   "Fremont/Seattle (Downtown)":"315",
   "Central District/Holly Park":"1027",
   "Kenmore/Richmond Highlands":"596",
   "Clyde Hill/Renton":"150",
   "Renton Boeing/Richmond Highlands":"1007",
   "Maple Leaf/Seattle (Downtown)":"771",
   "Central District/Madrona":"642",
   "Beacon Hill/Capitol Hill":"614",
   "Kennydale/Newport Hills":"380",
   "Kirkland/Renton Boeing":"174",
   "Admiral District/Riverton Heights":"406",
   "Duwamish Boeing/First Hill":"825",
   "Fauntleroy/Gatewood":"277",
   "Admiral District/Beacon Hill":"862",
   "Kingsgate/Totem Lake":"215",
   "Admiral District/Seattle (Downtown)":"755",
   "Montlake/Tukwila":"475",
   "Green Lake/Loyal Heights":"696",
   "Overlake/Totem Lake":"195",
   "Totem Lake/University District":"210",
   "Columbia City/SODO":"366",
   "Rose Hill/Seattle (Downtown)":"752",
   "Overlake/Shoreline":"239",
   "Avondale/Kirkland":"164",
   "Blue Ridge/Seattle (Downtown)":"630",
   "Bellevue (Downtown)/Burien":"1158",
   "Seattle (Downtown)/Totem Lake":"202",
   "Des Moines/McMicken Heights":"1171",
   "Seattle (Downtown)/Twin Lakes":"32",
   "Rainier Beach/Renton":"121",
   "Juanita/Montlake":"1127",
   "Houghton/Kenmore":"592",
   "Medina/Woodinville":"895",
   "Medina/Totem Lake":"206",
   "Bothell/Lake Forest Park":"1052",
   "Kenmore/Renton":"126",
   "Midway/Twin Lakes":"29",
   "Phinney Ridge/University District":"527",
   "Richmond Beach/Shoreline":"661",
   "Kennydale/SODO":"339",
   "Montlake/SODO":"360",
   "Bellevue (Downtown)/SODO":"369",
   "Seattle (Downtown)/South Lake Union":"781",
   "Innis Arden/South Lake Union":"494",
   "Georgetown/Star Lake":"652",
   "Eastgate/University District":"1088",
   "Renton Boeing/Riverton Heights":"408",
   "Georgetown/Normandy Park":"1084",
   "Kent Boeing/Southcenter":"377",
   "Duwamish Boeing/Seattle (Downtown)":"757",
   "Crown Hill/Queen Anne":"678",
   "Beaux Arts/Montlake":"1132",
   "Auburn/Twin Lakes":"31",
   "Lake City/Shoreline":"303",
   "Newport Hills/White Center":"8",
   "Federal Way/Sea-Tac Airport":"1174",
   "Eastgate/Kirkland":"176",
   "Eastgate/North Bend":"456",
   "Ravenna/Sand Point":"1119",
   "Mount Baker/Rainier Beach":"423",
   "Bellevue (East)/Education Hill":"41",
   "Kennydale/Montlake":"391",
   "Bitter Lake/South Kirkland":"714",
   "Newport Hills/Renton Highlands":"572",
   "Kent Boeing/SODO":"338",
   "Factoria/Northgate":"981",
   "Fall City/Snoqualmie":"913",
   "Queen Anne/Seattle (Downtown)":"679",
   "Green Lake/Montlake":"887",
   "Kenmore/Ravenna":"601",
   "Fairwood/Seattle (Downtown)":"329",
   "Eastgate/First Hill":"831",
   "Kent/Totem Lake":"70",
   "Central District/Ravenna":"1031",
   "Issaquah/North Bend":"455",
   "Houghton/Kingsgate":"818",
   "Beacon Hill/Renton":"130",
   "Bellevue (Downtown)/University District":"1110",
   "Jackson Park/Maple Leaf":"849",
   "Bellevue (Downtown)/Seattle (Downtown)":"798",
   "Bellevue (Downtown)/Kingsgate":"1187",
   "Finn Hill/Seattle (Downtown)":"796",
   "Innis Arden/Kenmore":"487",
   "Bothell/Cottage Lake":"961",
   "Richmond Highlands/Shoreline":"1013",
   "Capitol Hill/Montlake":"619",
   "Bothell/Rainier Beach":"425",
   "Seattle (Downtown)/Timberlane":"635",
   "Montlake/Wallingford":"1130",
   "Bitter Lake/Eastgate":"1092",
   "North Beach/University District":"1041",
   "Madison Park/Madrona":"332",
   "Jackson Park/Wedgwood":"844",
   "Beaux Arts/Sea-Tac Airport":"1189",
   "Issaquah/Montlake":"971",
   "Renton Boeing/Shoreline":"1059",
   "Kirkland/Wedgwood":"169",
   "Loyal Heights/South Lake Union":"703",
   "Bothell/Maple Leaf":"1074",
   "SODO/White Center":"3",
   "Eastgate/Houghton":"810",
   "Juanita/Medina":"996",
   "Bellevue (Downtown)/Kenmore":"608",
   "Bitter Lake/Madrona":"645",
   "South Kirkland/University District":"712",
   "Mount Baker/Rainier Valley":"563",
   "Beacon Hill/West Seattle Junction":"861",
   "Montlake/Renton":"144",
   "Factoria/Renton":"132",
   "Fauntleroy/Seattle (Downtown)":"732",
   "Capitol Hill/Holly Park":"617",
   "Lake Meridian/Maple Valley":"194",
   "First Hill/Jackson Park":"821",
   "Kent/Maple Valley":"89",
   "Auburn/Star Lake":"646",
   "Midway/Star Lake":"535",
   "First Hill/White Center":"12",
   "Bothell/Rose Hill":"919",
   "Central District/White Center":"18",
   "Des Moines/Midway":"546",
   "Ballard/Greenwood":"439",
   "Bryn Mawr/Rainier Beach":"412",
   "Burien/Georgetown":"1149",
   "Maple Leaf/Ravenna":"1071",
   "Houghton/Wedgwood":"804",
   "Cottage Lake/Woodinville":"894",
   "Renton/Totem Lake":"113",
   "Jackson Park/Richmond Highlands":"846",
   "Crown Hill/South Lake Union":"728",
   "Fremont/Queen Anne":"313",
   "Central District/Midway":"540",
   "Sea-Tac Airport/White Center":"24",
   "Kingsgate/Montlake":"1128",
   "Central District/Delridge":"509",
   "Federal Way/First Hill":"841",
   "Crown Hill/Green Lake":"720",
   "Bitter Lake/Overlake":"241",
   "Midway/Seattle (Downtown)":"536",
   "Beacon Hill/Central District":"865",
   "Fauntleroy/Vashon Island":"736",
   "Arbor Heights/West Seattle Junction":"945",
   "Clyde Hill/SODO":"368",
   "Ballard/Queen Anne":"684",
   "Kingsgate/Seattle (Downtown)":"795",
   "Northgate/Queen Anne":"691",
   "Central District/Wedgwood":"928",
   "Midway/Sea-Tac Airport":"545",
   "Kent/Tukwila":"76",
   "Mount Baker/Seattle (Downtown)":"779",
   "Newport Hills/Seattle (Downtown)":"570",
   "Fairwood/Tukwila":"328",
   "Delridge/First Hill":"503",
   "Queen Anne/Wedgwood":"682",
   "Bothell/Wedgwood":"938",
   "Kennydale/Lake Forest Park":"388",
   "Overlake/Renton":"114",
   "Lake City/Medina":"293",
   "Federal Way/Seattle (Downtown)":"792",
   "Columbia City/First Hill":"840",
   "Bellevue (East)/Medina":"46",
   "Jackson Park/Seattle (Downtown)":"746",
   "Bellevue (Downtown)/Bothell":"1148",
   "Bellevue (East)/Crossroads":"51",
   "Eastlake/University District":"106",
   "Lake Meridian/Tukwila":"188",
   "Kent/University District":"90",
   "First Hill/Madrona":"640",
   "Maple Leaf/Montlake":"1072",
   "Rainier Valley/University District":"562",
   "Clyde Hill/Factoria":"982",
   "Montlake/Totem Lake":"211",
   "Duwamish Boeing/Georgetown":"957",
   "Renton/University District":"143",
   "Alki/West Seattle Junction":"946",
   "Georgetown/Tukwila":"476",
   "Bitter Lake/Mercer Island":"1081",
   "South Kirkland/Totem Lake":"201",
   "Loyal Heights/Sand Point":"705",
   "Gatewood/Seattle (Downtown)":"278",
   "Blue Ridge/Fremont":"312",
   "Ballard/Broadview":"1022",
   "Burien/Sea-Tac Airport":"1157",
   "Totem Lake/Woodinville":"204",
   "Black Diamond/Maple Valley":"1004",
   "Eastgate/Medina":"988",
   "Education Hill/Redmond":"249",
   "Lake City/Maple Leaf":"297",
   "Central District/Greenwood":"440",
   "Burien/Delridge":"514",
   "Juanita/South Kirkland":"715",
   "Newport Hills/University District":"579",
   "Eastgate/Newport Hills":"578",
   "Admiral District/Fauntleroy":"734",
   "Crown Hill/Loyal Heights":"694",
   "Houghton/Montlake":"812",
   "Broadview/Shoreline":"1138",
   "Finn Hill/Kenmore":"607",
   "Queen Anne/Rainier Beach":"415",
   "Bellevue (Downtown)/Juanita":"1185",
   "North Bend/Preston":"457",
   "Issaquah/Mercer Island":"967",
   "Covington/Kent":"60",
   "Delridge/Georgetown":"513",
   "Montlake/Woodinville":"900",
   "Bitter Lake/Phinney Ridge":"532",
   "Bellevue (Downtown)/Maple Leaf":"1078",
   "Sea-Tac/Tukwila":"480",
   "Kennydale/Sea-Tac Airport":"398",
   "Redmond/Renton Boeing":"262",
   "Maple Leaf/Wedgwood":"930",
   "Green Lake/Northgate":"890",
   "Broadview/South Lake Union":"1133",
   "Jackson Park/Overlake":"225",
   "Phinney Ridge/Seattle (Downtown)":"523",
   "Bothell/Newport Hills":"581",
   "Green Lake/Redmond":"255",
   "Kent Boeing/Sea-Tac":"376",
   "Bitter Lake/Fremont":"325",
   "Maple Leaf/Richmond Highlands":"1008",
   "Richmond Highlands/Totem Lake":"207",
   "Broadview/Queen Anne":"690",
   "SODO/Star Lake":"346",
   "Delridge/Sea-Tac Airport":"516",
   "Green Lake/Wedgwood":"878",
   "Lake Forest Park/Renton Boeing":"1047",
   "Newport Hills/SODO":"345",
   "Finn Hill/Kirkland":"185",
   "Northgate/Wedgwood":"939",
   "Renton Boeing/Southcenter":"1065",
   "Bitter Lake/Crown Hill":"731",
   "Federal Way/Northeast Tacoma":"860",
   "Magnolia/Seattle (Downtown)":"756",
   "Medina/North City":"905",
   "Greenwood/Innis Arden":"429",
   "Kingsgate/Renton Boeing":"1062",
   "Auburn/Sea-Tac":"674",
   "First Hill/Tukwila":"467",
   "Delridge/Sea-Tac":"515",
   "Admiral District/Delridge":"506",
   "Central District/Loyal Heights":"698",
   "Bitter Lake/Queen Anne":"692",
   "Clyde Hill/Newport Hills":"585",
   "Beacon Hill/Holly Park":"866",
   "Kingsgate/Newport Hills":"586",
   "Northgate/Richmond Beach":"662",
   "Eastgate/Seattle (Downtown)":"775",
   "Riverton Heights/Seattle (Downtown)":"404",
   "Georgetown/White Center":"21",
   "Bellevue (Downtown)/Lake Forest Park":"1055",
   "Beacon Hill/Rainier Valley":"553",
   "First Hill/Kenmore":"593",
   "Bellevue (Downtown)/Ravenna":"1118",
   "Bothell/English Hill":"627",
   "Redmond/Seattle (Downtown)":"253",
   "Central District/North Beach":"1026",
   "Kennydale/Sea-Tac":"395",
   "Kennydale/Kirkland":"159",
   "McMicken Heights/Southcenter":"1172",
   "Capitol Hill/Duwamish Boeing":"615",
   "Kennydale/Richmond Highlands":"387",
   "Central District/Mercer Island":"1028",
   "Riverton Heights/West Seattle Junction":"405",
   "Bellevue (Downtown)/Clyde Hill":"1181",
   "Factoria/Newport Hills":"573",
   "Lake Meridian/Midway":"189",
   "Seattle (Downtown)/Vashon Island":"788",
   "Holly Park/Rainier Valley":"560",
   "Juanita/Seattle (Downtown)":"794",
   "Georgetown/Holly Park":"1069",
   "Bellevue (Downtown)/Jackson Park":"859",
   "Twin Lakes/University District":"35",
   "Beaux Arts/Delridge":"519",
   "Overlake/South Kirkland":"221",
   "Innis Arden/University District":"493",
   "Covington/Kent East Hill":"65",
   "Clyde Hill/Eastgate":"1093",
   "Central District/Jackson Park":"847",
   "Kent East Hill/Midway":"539",
   "Columbia City/West Seattle Junction":"947",
   "Kent/Midway":"77",
   "North City/Richmond Highlands":"906",
   "Georgetown/Riverton Heights":"409",
   "Alki/Beacon Hill":"867",
   "Ballard/Wedgwood":"927",
   "Eastlake/Montlake":"108",
   "Sand Point/Wedgwood":"943",
   "Maple Leaf/North City":"907",
   "Juanita/Kenmore":"605",
   "Bellevue (East)/Montlake":"49",
   "Arbor Heights/White Center":"17",
   "Eastlake/Maple Leaf":"105",
   "Georgetown/Midway":"542",
   "Delridge/Duwamish Boeing":"507",
   "Cottage Lake/English Hill":"626",
   "Rainier Valley/South Lake Union":"565",
   "Lake Forest Park/Wedgwood":"929",
   "Kent/Overlake":"71",
   "Burien/Southcenter":"1160",
   "Bitter Lake/Wedgwood":"940",
   "Kenmore/Kirkland":"161",
   "Finn Hill/Totem Lake":"216",
   "Maple Leaf/Northgate":"1076",
   "Arbor Heights/SODO":"354",
   "Broadview/Phinney Ridge":"530",
   "Renton/Seattle (Downtown)":"128",
   "Central District/Lake City":"294",
   "Innis Arden/Jackson Park":"490",
   "Bellevue (Downtown)/Sammamish":"59",
   "Bothell/University District":"1102",
   "Medina/South Kirkland":"709",
   "Newport Hills/Renton Boeing":"577",
   "Juanita/Woodinville":"902",
   "Houghton/Renton Boeing":"809",
   "Kent/Star Lake":"80",
   "Beaux Arts/Eastgate":"1096",
   "Crossroads/Factoria":"983",
   "Factoria/Redmond":"260",
   "Kent/Newport Hills":"78",
   "Green Lake/Richmond Highlands":"880",
   "Bellevue (Downtown)/Sea-Tac Airport":"1188",
   "Fauntleroy/SODO":"348",
   "Lake Forest Park/Shoreline":"1053",
   "Burien/Renton Boeing":"1060",
   "Lake Forest Park/University District":"1049",
   "Kenmore/Maple Leaf":"599",
   "Bothell/Lake City":"302",
   "Central District/Issaquah":"966",
   "Lake Forest Park/Seattle (Downtown)":"769",
   "Medina/Shoreline":"992",
   "Normandy Park/Seattle (Downtown)":"773",
   "Loyal Heights/Rainier Valley":"549",
   "Arbor Heights/Gatewood":"281",
   "Blue Ridge/Crown Hill":"629",
   "Jackson Park/Lake City":"289",
   "First Hill/Wedgwood":"824",
   "Fremont/Shoreline":"323",
   "Federal Way/Kent":"93",
   "Auburn/Overlake":"220",
   "Delridge/Kennydale":"379",
   "Broadview/Richmond Beach":"660",
   "Beaux Arts/Burien":"1161",
   "Delridge/Riverton Heights":"402",
   "Kennydale/Medina":"386",
   "Kent Boeing/Lake Meridian":"187",
   "Seattle (Downtown)/Tukwila":"466",
   "Kenmore/Kennydale":"381",
   "Delridge/Fauntleroy":"501",
   "Bothell/Redmond":"267",
   "Fairwood/Southcenter":"330",
   "Greenwood/Queen Anne":"433",
   "Renton/Tukwila":"123",
   "Avondale/Woodinville":"738",
   "Loyal Heights/Seattle (Downtown)":"695",
   "Bitter Lake/Greenwood":"448",
   "Blue Ridge/Phinney Ridge":"520",
   "Mercer Island/Sammamish":"57",
   "Avondale/Cottage Lake":"740",
   "Eastgate/Renton Boeing":"1057",
   "Issaquah/Northgate":"973",
   "Overlake/Seattle (Downtown)":"223",
   "Bellevue (East)/Redmond":"40",
   "Fauntleroy/Tukwila":"465",
   "Ballard/Loyal Heights":"697",
   "Innis Arden/Lake Forest Park":"492",
   "Renton/Renton Boeing":"139",
   "Renton/Southcenter":"154",
   "Kennydale/Shoreline":"393",
   "Redmond/Woodinville":"256",
   "Renton/Skyway":"135",
   "Bellevue (Downtown)/Woodinville":"904",
   "Central District/Duwamish Boeing":"956",
   "Admiral District/Rainier Valley":"557",
   "Seattle (Downtown)/Skyway":"763",
   "Kingsgate/Redmond":"270",
   "Jackson Park/North City":"843",
   "Broadview/Jackson Park":"854",
   "Madrona/Mount Baker":"643",
   "Issaquah/Medina":"965",
   "Eastlake/South Lake Union":"109",
   "Holly Park/Queen Anne":"687",
   "Rainier Valley/West Seattle Junction":"556",
   "Lake Forest Park/Renton":"138",
   "Kent Boeing/Tukwila":"371",
   "Bothell/Woodinville":"901",
   "Kent/Southcenter":"99",
   "Ballard/North Beach":"1018",
   "Greenwood/Shoreline":"447",
   "Auburn/Renton":"127",
   "Duvall/Overlake":"242",
   "Burien/Tukwila":"477",
   "Ballard/University District":"1019",
   "Richmond Highlands/University District":"1009",
   "Lake City/Renton":"116",
   "Admiral District/Alki":"949",
   "Ballard/Montlake":"1020",
   "Auburn/Seattle (Downtown)":"667",
   "Jackson Park/Richmond Beach":"657",
   "Lake Forest Park/Woodinville":"896",
   "Gatewood/Vashon Island":"282",
   "Green Lake/Maple Leaf":"883",
   "Houghton/Newport Hills":"571",
   "Duwamish Boeing/SODO":"353",
   "Factoria/Issaquah":"964",
   "Ballard/Twin Lakes":"34",
   "Capitol Hill/University District":"618",
   "First Hill/University District":"832",
   "Bellevue (Downtown)/Delridge":"517",
   "Crown Hill/Mount Baker":"726",
   "Jackson Park/Montlake":"852",
   "Redmond/University District":"265",
   "Eastgate/Snoqualmie":"1090",
   "Georgetown/Renton":"146",
   "Greenwood/Mount Baker":"443",
   "Kenmore/Overlake":"219",
   "Bellevue (Downtown)/Education Hill":"666",
   "Medina/Tukwila":"472",
   "Kent East Hill/Timberlane":"636",
   "Burien/Seattle (Downtown)":"787",
   "Auburn/Kennydale":"382",
   "Loyal Heights/Queen Anne":"677",
   "Finn Hill/Kingsgate":"1186",
   "Delridge/Newport Hills":"499",
   "Bellevue (East)/Clyde Hill":"50",
   "Fremont/Northgate":"324",
   "Madison Park/Seattle (Downtown)":"333",
   "Capitol Hill/South Lake Union":"620",
   "Medina/Newport Hills":"574",
   "Central District/Green Lake":"881",
   "Bellevue (Downtown)/Kennydale":"399",
   "Renton/Riverton Heights":"120",
   "Houghton/Kennydale":"384",
   "Federal Way/Star Lake":"653",
   "Capitol Hill/White Center":"9",
   "Central District/Mount Baker":"1032",
   "Des Moines/Seattle (Downtown)":"800",
   "Kingsgate/Shoreline":"1154",
   "Overlake/Rose Hill":"228",
   "Bitter Lake/Rainier Valley":"566",
   "Seattle (Downtown)/University District":"777",
   "First Hill/Issaquah":"826",
   "Crossroads/Kirkland":"182",
   "Des Moines/Star Lake":"655",
   "Greenwood/Phinney Ridge":"430",
   "Lake City/Lake Forest Park":"296",
   "Admiral District/Tukwila":"469",
   "Madrona/Queen Anne":"638",
   "Montlake/South Kirkland":"713",
   "Kennydale/Kent":"75",
   "Seattle (Downtown)/Snoqualmie":"783",
   "Lake Meridian/Timberlane":"190",
   "Bellevue (Downtown)/Finn Hill":"1190",
   "Rainier Beach/Wedgwood":"419",
   "Factoria/Rose Hill":"914",
   "Alki/Delridge":"511",
   "Medina/Redmond":"261",
   "Broadview/Innis Arden":"495",
   "Kent/Timberlane":"79",
   "Newport Hills/Totem Lake":"198",
   "Green Lake/University District":"884",
   "Auburn/SODO":"347",
   "Bellevue (East)/Kirkland":"38",
   "Houghton/Juanita":"817",
   "Des Moines/Normandy Park":"1086",
   "Bitter Lake/Jackson Park":"857",
   "Beacon Hill/Rainier Beach":"418",
   "First Hill/Queen Anne":"680",
   "Magnolia/Wedgwood":"925",
   "North Beach/Queen Anne":"686",
   "Factoria/Medina":"977",
   "Holly Park/Skyway":"1001",
   "Northgate/Seattle (Downtown)":"789",
   "Fremont/University District":"320",
   "Ravenna/Woodinville":"899",
   "Loyal Heights/Montlake":"702",
   "Algona/Auburn":"670",
   "Crown Hill/Rainier Valley":"550",
   "Lake City/Seattle (Downtown)":"287",
   "Kent/Kent Boeing":"74",
   "Eastgate/Mercer Island":"1079",
   "Kenmore/South Kirkland":"590",
   "Crossroads/Eastgate":"1094",
   "Duwamish Boeing/Midway":"538",
   "Eastlake/Jackson Park":"103",
   "First Hill/Madison Park":"334",
   "Queen Anne/South Lake Union":"689",
   "Ballard/Northgate":"1023",
   "Kenmore/University District":"600",
   "Montlake/Overlake":"238",
   "Gatewood/SODO":"273",
   "Mount Baker/North Beach":"1042",
   "Shoreline/Totem Lake":"213",
   "Midway/Tukwila":"462",
   "Bellevue (Downtown)/Overlake":"246",
   "Bellevue (Downtown)/Wedgwood":"942",
   "Richmond Highlands/SODO":"357",
   "Bellevue (East)/Factoria":"45",
   "Beaux Arts/Mercer Island":"1083",
   "Burien/Sea-Tac":"1156",
   "Kirkland/Mercer Island":"175",
   "Alki/Columbia City":"1087",
   "Bellevue (Downtown)/Issaquah":"975",
   "Kirkland/Richmond Highlands":"172",
   "Mercer Island/Wedgwood":"931",
   "Greenwood/University District":"442",
   "Renton/Renton Highlands":"131",
   "Medina/Northgate":"993",
   "Black Diamond/Renton":"136",
   "Kirkland/Overlake":"157",
   "Central District/Crown Hill":"723",
   "Kennydale/White Center":"4",
   "SODO/Vashon Island":"365",
   "Northeast Tacoma/Twin Lakes":"33",
   "Clyde Hill/Wedgwood":"941",
   "Federal Way/Midway":"544",
   "Des Moines/Tukwila":"483",
   "Capitol Hill/Seattle (Downtown)":"612",
   "Auburn/Kent Boeing":"372",
   "Ballard/Crown Hill":"722",
   "Bellevue (Downtown)/Renton":"153",
   "Phinney Ridge/Queen Anne":"521",
   "Bellevue (Downtown)/Tukwila":"482",
   "Arbor Heights/Seattle (Downtown)":"759",
   "Renton/Shoreline":"147",
   "Greenwood/Richmond Highlands":"438",
   "Houghton/Kent":"83",
   "Bellevue (Downtown)/South Kirkland":"718",
   "Clyde Hill/Medina":"995",
   "Lake Forest Park/Southcenter":"1056",
   "Clyde Hill/Maple Leaf":"1077",
   "Bothell/Finn Hill":"1147",
   "Lake City/Montlake":"300",
   "Montlake/Ravenna":"1113",
   "First Hill/Mount Baker":"834",
   "Renton Boeing/Renton Highlands":"872",
   "Central District/Rainier Beach":"421",
   "Kirkland/Renton":"111",
   "Admiral District/Southcenter":"951",
   "Bellevue (Downtown)/Eastgate":"1095",
   "Bothell/Holly Park":"1068",
   "Mount Baker/University District":"1099",
   "Maple Valley/Renton":"142",
   "Tukwila/West Seattle Junction":"468",
   "Bellevue (Downtown)/Montlake":"1131",
   "Green Lake/Overlake":"226",
   "Jackson Park/Ravenna":"851",
   "Kenmore/Redmond":"247",
   "Auburn/Kingsgate":"675",
   "Clyde Hill/University District":"1106",
   "Riverton Heights/Tukwila":"401",
   "South Lake Union/University District":"1101",
   "Greenwood/Seattle (Downtown)":"436",
   "Phinney Ridge/Wallingford":"533",
   "Crossroads/Education Hill":"665",
   "North Beach/Sand Point":"1046",
   "Central District/Rainier Valley":"558",
   "Bellevue (Downtown)/Bitter Lake":"1167",
   "First Hill/Rainier Beach":"417",
   "Fremont/Green Lake":"316",
   "Bellevue (Downtown)/Shoreline":"1155",
   "Holly Park/Seattle (Downtown)":"770",
   "Bitter Lake/Central District":"1038",
   "Blue Ridge/Queen Anne":"628",
   "Magnolia/University District":"953",
   "Crown Hill/Northgate":"730",
   "Des Moines/Federal Way":"1175",
   "Broadview/Northgate":"1139",
   "University District/Woodinville":"898",
   "Bitter Lake/Rainier Beach":"427",
   "Innis Arden/Northgate":"497",
   "Redmond/Rose Hill":"257",
   "Capitol Hill/Rainier Beach":"414",
   "First Hill/Midway":"537",
   "Bothell/Renton Highlands":"874",
   "Finn Hill/Juanita":"1184",
   "Bellevue (Downtown)/Crossroads":"1182",
   "Central District/Seattle (Downtown)":"767",
   "Fremont/Phinney Ridge":"311",
   "Jackson Park/Lake Forest Park":"848",
   "Bitter Lake/First Hill":"839",
   "South Kirkland/Wedgwood":"708",
   "Capitol Hill/Columbia City":"623",
   "Delridge/Gatewood":"276",
   "Central District/University District":"1030",
   "Gatewood/White Center":"2",
   "Beaux Arts/Kennydale":"400",
   "Eastlake/Northgate":"110",
   "Enumclaw/Muckleshoot Reservation":"451",
   "Lake City/Woodinville":"291",
   "Kent/Kingsgate":"95",
   "Bothell/Renton Boeing":"1058",
   "Green Lake/South Lake Union":"888",
   "Broadview/Richmond Highlands":"1011",
   "Green Lake/Shoreline":"889",
   "Renton Boeing/Sea-Tac Airport":"1063",
   "Capitol Hill/Madison Park":"331",
   "Sand Point/University District":"1111",
   "Mercer Island/University District":"1080",
   "Houghton/University District":"811",
   "Eastgate/Overlake":"236",
   "Montlake/North Beach":"1043",
   "Innis Arden/Richmond Beach":"488"
}